### ISSUE TITLE
在一定时间段内，发送消息时，可以重用媒体文件

### ISSUE THREAD

**Issue by danni-cool** [danni-cool/wechatbot-webhook#101]
计划通过 `redis` 对所有需要下载的文件缓存一段时间，提高消息发送速度

**Comment by shaojun-tes** [comment]
希望redis这块是可选项，因为我的场景只是接收文本消息做后续的逻辑处理即可。是跑在退役手机里的termux的，以此来省电同时让退役手机有发挥余热的机会。

**Comment by danni-cool** [comment]
get
