### ISSUE TITLE
如何将chatgpt接入wechatbot-webhook机器人

### ISSUE THREAD

**Issue by birdxs** [danni-cool/wechatbot-webhook#105]
我使用这个项目https://github.com/pandora-next/deploy
搭建了chatgpt，但是每次使用都是通过浏览器访问。
本项目可以创建微信机器人，我就想把chatgpt接入微信，这样实现在手机微信与chatgpt对话。
不知道能不能实现以及如何实现，请教大佬赐教，或者感兴趣的一起讨论一下。

**Comment by danni-cool** [comment]
看了下 pandora-next 这个项目，里面有个backend-api/conversiation 支持作为纯 api调用，如果想就用这个项目集成你可以fork项目，改 https://github.com/danni-cool/wechatbot-webhook/blob/ea42fbbb958b7af40a8b8902815bfb9c6e450f34/src/service/webhook.js#L78 里面源码为你调用 pandora-next 的接口，并且返回值就好了，当然你还要关注下token。

**Comment by danni-cool** [comment]
如果不想该项目专用chatgpt，适合接入n8n等自动化流里面，当然规则还得你自己写

**Comment by birdxs** [comment]
> 看了下 pandora-next 这个项目，里面有个backend-api/conversiation 支持作为纯 api调用，如果想就用这个项目集成你可以fork项目，改
> 
> https://github.com/danni-cool/wechatbot-webhook/blob/ea42fbbb958b7af40a8b8902815bfb9c6e450f34/src/service/webhook.js#L78
> 
> 里面源码为你调用 pandora-next 的接口，然后得到返回值，在调用发消息api即可

感谢大佬解答，作为小白看了你答复的，我还是不清楚该怎么部署，接下来我自己好好研究下。

**Comment by danni-cool** [comment]
其实基于http协议去把chatgpt流程单独写就好了，用这个项目还是要懂点开发，也许你也可以问问chatgpt要如何操作
