### ISSUE TITLE
如何与微信公众号的菜单交互

### ISSUE THREAD

**Issue by nuym** [danni-cool/wechatbot-webhook#106]
比如我想点击一个公众号菜单中的”获取链接“，公众号就会给我推送链接地址，请问这个能否实现，不胜感激！

**Comment by danni-cool** [comment]
这个就比较复杂了，涉及到微信公众号开发的api处理业务 -> [触发了自定义菜单事件](https://developers.weixin.qq.com/doc/offiaccount/Custom_Menus/Custom_Menu_Push_Events.html)  -> 调用 wechatbot-webhook api ，当然这个不是本项目要去解决的问题，你得自行解决公众号开发的一些问题

**Comment by danni-cool** [comment]
公众号推链接地址这个貌似是微信公众号开发的领域，和本项目没有关系哦

**Comment by nuym** [comment]
> 公众号推链接地址这个貌似是微信公众号开发的领域，和本项目没有关系哦

你可能理解错我的意思了，我的意思是用webhook进行公众号菜单的交互。

**Comment by danni-cool** [comment]
你期望公众号菜单点击了 -> 推送消息到个人微信吗

**Comment by nuym** [comment]
> 你期望公众号菜单点击了 -> 推送消息到个人微信吗

微信登陆到webhook -> 调用webhook实现类似于点击公众号按钮的交互->公众号发送消息到微信->webhook收到消息->后续的开发

**Comment by danni-cool** [comment]
https://github.com/silenceper/wechat

**Comment by xiaopeng12138** [comment]
比如说舞萌 | 中二这个公众号有一个按钮，是玩家二维码，按一下会返回一个链接，如果能实现自动化就好了。
![Screenshot_2024-02-20-13-33-14-82_e39d2c7de19156b0683cd93e8735f348](https://github.com/danni-cool/wechatbot-webhook/assets/46627911/ac3d4162-918a-4f2f-9f52-20b0fe335e8d)

**Comment by nuym** [comment]
> 比如说舞萌 | 中二这个公众号有一个按钮，是玩家二维码，按一下会返回一个链接，如果能实现自动化就好了。
> 
> ![Screenshot_2024-02-20-13-33-14-82_e39d2c7de19156b0683cd93e8735f348](https://github.com/danni-cool/wechatbot-webhook/assets/46627911/ac3d4162-918a-4f2f-9f52-20b0fe335e8d)
> 
> 

猜对了

**Comment by xiaopeng12138** [comment]
> > 比如说舞萌 | 中二这个公众号有一个按钮，是玩家二维码，按一下会返回一个链接，如果能实现自动化就好了。
> > 
> > ![Screenshot_2024-02-20-13-33-14-82_e39d2c7de19156b0683cd93e8735f348](https://github.com/danni-cool/wechatbot-webhook/assets/46627911/ac3d4162-918a-4f2f-9f52-20b0fe335e8d)
> > 
> > 
> 
> 猜对了

原来都是mai批（
