### ISSUE TITLE
可以判断消息是否引用（回复）了某个消息吗？

### ISSUE THREAD

**Issue by Cassius0924** [danni-cool/wechatbot-webhook#107]
可以判断消息是否引用（回复）了某个消息吗？

我在 [source 示例](https://github.com/danni-cool/wechatbot-webhook/blob/main/docs/recvdApi.example.md#formdatasource-string) 里没找到对应字段。

如果目前不支持，问一下目前底层Linux微信是否支持引用回复？

**Comment by danni-cool** [comment]
@Cassius0924 https://github.com/danni-cool/wechatbot-webhook/issues/38#issuecomment-1774336597
