### ISSUE TITLE
发送图片偶尔失败

### ISSUE THREAD

**Issue by panyushan-jade** [danni-cool/wechatbot-webhook#110]
![Uploading 企业微信截图_17045129948562.png…]()

**Comment by panyushan-jade** [comment]
![企业微信截图_17045129948562](https://github.com/danni-cool/wechatbot-webhook/assets/48422428/4fc22603-0a8d-4883-a1fe-33fba6a57cb7)

**Comment by danni-cool** [comment]
1205 是已知的wechaty底层问题，重启解决吧，@人web协议不支持

**Comment by panyushan-jade** [comment]
> 1205 是已知的wechaty底层问题，重启解决吧，@人web协议不支持

好的，感谢
