### ISSUE TITLE
help /healthz

### ISSUE THREAD

**Issue by stingoChen** [danni-cool/wechatbot-webhook#111]
你好 请问下 /healthz 接口如何使用，可以提供一个例子不。

**Comment by danni-cool** [comment]
http://localhost:3001/healthz?token=YOUR_PERSONAL_TOKEN

**Comment by stingoChen** [comment]
> http://localhost:3001/healthz?token=YOUR_PERSONAL_TOKEN

为啥我得到了一个 这个结果。
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /healthz</pre>
</body>
</html>

**Comment by danni-cool** [comment]
login 接口可以访问吗

**Comment by stingoChen** [comment]
login 接口 正常

**Comment by danni-cool** [comment]
确保代码是最新的，对应version版本是2.5.0

**Comment by stingoChen** [comment]
ok 感谢
