### ISSUE TITLE
公众号的推送通知能收的到吗？

### ISSUE THREAD

**Issue by woshizhangxiaohao** [danni-cool/wechatbot-webhook#112]
你好。公众号的推送通知能收的到吗？目前公众号的客服消息是能接受到的。就是不太清楚公众号的推送通知能否收的到。

**Comment by danni-cool** [comment]
你可以测试下，一般是以urlLink类型消息收到的

**Comment by woshizhangxiaohao** [comment]
@danni-cool 你好，我测试了，推送发过来，命令行是空的状态。

**Comment by woshizhangxiaohao** [comment]
@danni-cool 我应该怎么处理才能拿到公众号推送的消息呢？可以问一下吗？

**Comment by danni-cool** [comment]
你得配置收消息api才会给你推送消息，api收到的结构大概长这样

```
"source": 
"{"room":"","to":{"_events":{},"_eventsCount":0,"id":"@c11765997b781b129b0eb1b96ab956f67edf","payload":{"alias":"","avatar":"/cgi-bin/mmwebwx-bin/webwxgeticon?seq=131276&username=@c117651231b129b0fbee4d956f67edf&skey=@crypt_a3e59205_089eb93","friend":false,"gender":1,"id":"@c11765997b781b12asdfs96ab97edf","name":"danni-cool","phone":[],"signature":"","star":false,"type":1}},"from":{"_events":{},"_eventsCount":0,"id":"@2f8ccf3ebd","payload":{"address":"","alias":"","avatar":"/cgi-bin/mmwebwx-bin/webwxgeticon?seq=69&username=@2f15a37bd&skey=@crypt_ab2bd93","city":"","friend":true,"gender":0,"id":"@2f81a715ce15a37bd","name":"测试公众号","phone":[],"province":"","signature":"","star":false,"weixin":"","type":2}}}",
"isSystemEvent": 
"0",
"isMentioned": 
"0",
"type": 
"urlLink",
"content": 
"{"description":"这是一篇测试文章，由daniel-cool编写","thumbnailUrl":"https://mmbiz.qpic.cn/sz_mmbiz_jpg/sdfsfd5mWib35PfOe57uNsTsdfsfd4VibRceqxWzw/640?wxtype=jpeg&wxfrom=0","title":"测试文章1","url":"http://mp.weixin.qq.com/s?__biz=MzkwMTIxMTAyMA==&mid=100000017&idx=1&sn=a452516069433123e6f18c3db20c9&chksm=4012377f277cefee4ee74dc92b8bcec76703f3a189e8836365d746ea2c21278ce8d9df&scene=0&xtrack=2&previewkey=A5DcAfLjIgnvxUe%25252Bez345MNS9bJ52F0By7ITJA%25253D#rd"}"
}
```

**Comment by UnknowZang** [comment]
> 你得配置收消息api才会给你推送消息，api收到的结构大概长这样
> 
> ```
> "source": 
> "{"room":"","to":{"_events":{},"_eventsCount":0,"id":"@c11765997b781b129b0eb1b96ab956f67edf","payload":{"alias":"","avatar":"/cgi-bin/mmwebwx-bin/webwxgeticon?seq=131276&username=@c117651231b129b0fbee4d956f67edf&skey=@crypt_a3e59205_089eb93","friend":false,"gender":1,"id":"@c11765997b781b12asdfs96ab97edf","name":"danni-cool","phone":[],"signature":"","star":false,"type":1}},"from":{"_events":{},"_eventsCount":0,"id":"@2f8ccf3ebd","payload":{"address":"","alias":"","avatar":"/cgi-bin/mmwebwx-bin/webwxgeticon?seq=69&username=@2f15a37bd&skey=@crypt_ab2bd93","city":"","friend":true,"gender":0,"id":"@2f81a715ce15a37bd","name":"测试公众号","phone":[],"province":"","signature":"","star":false,"weixin":"","type":2}}}",
> "isSystemEvent": "0",
> "isMentioned": "0",
> "type": "urlLink",
> "content": "{"description":"这是一篇测试文章，由daniel-cool编写","thumbnailUrl":"https://mmbiz.qpic.cn/sz_mmbiz_jpg/sdfsfd5mw/640?wxtype=jpeg&wxfrom=0","title":"测试文章1","url":"http://mp.weixin.qq.com/s?__biz=MyMA==&mid=100017&idx=1&sn=a4529&chksm=40165d746ea&scene=0&xtrack=2&previewkey=A5Dc53D#rd"}"
> }
> ```
> 
> 交流可以在discord上找我 https://discord.gg/e7VbNAAn

微信公众号经验证返回了如上json体数据，其中参数’url‘应该是原文链接，但是无法访问到，请教有什么解析方法吗？

**Comment by danni-cool** [comment]
@UnknowZang 你应该提供问题数据，而不是引用我的数据
