### ISSUE TITLE
如何接收file类型的消息呢

### ISSUE THREAD

**Issue by bupojie888** [danni-cool/wechatbot-webhook#117]
如何接收file类型的消息呢 希望有大神回答一下  2024发发发

**Comment by danni-cool** [comment]
接收都是ok的，你需要先在服务端解析form-data -> 判断type 类型为file -> 保存二进制文件写入本地。
你也可以用n8n webhook 节点去接收，这个比较无缝

**Comment by bupojie888** [comment]
能加一下你微信吗 后期可能后一些有偿定制需求找你

**Comment by bupojie888** [comment]
![image](https://github.com/danni-cool/wechatbot-webhook/assets/75459234/914171de-c56a-4816-9ff2-cd1a5a999a35)

**Comment by danni-cool** [comment]
> 能加一下你微信吗 后期可能后一些有偿定制需求找你

感谢你的肯定，不过目前不接定制，社区驱动

**Comment by danni-cool** [comment]
> ![image](https://private-user-images.githubusercontent.com/75459234/295419694-914171de-c56a-4816-9ff2-cd1a5a999a35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTUzMTksIm5iZiI6MTcwNDg1NTAxOSwicGF0aCI6Ii83NTQ1OTIzNC8yOTU0MTk2OTQtOTE0MTcxZGUtYzU2YS00ODE2LTlmZjItY2QxYTVhOTk5YTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDAyNTAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMGFhODQ3ZmE3ZGQ2MTNlMjUxZThjMDg1NmUzZTQ5MzQyZmFkZGM4ODU4M2EyZTVjYTkwYmZjMWNhYzhjN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.axf5u6oDPUUrviU8qQwlIQQ3-oDr4wmTSS49sg_X1Ao)

可以配合这个食用 https://github.com/danni-cool/wechatbot-webhook/blob/main/docs/recvdApi.example.md#formdatacontent

**Comment by bupojie888** [comment]
**我这样写不对吗？ 获取的内容还是为空  你发的那个链接我没看明白? 我代码发你能帮我修改下吗？**

![image](https://github.com/danni-cool/wechatbot-webhook/assets/75459234/40d71070-dc86-449f-9625-0940dde7e9fb)

**Comment by danni-cool** [comment]
php 不太懂，先用formdata 解析，再用json解析一些json string

**Comment by bupojie888** [comment]
**这个是我接收的参数, $content 文本是没问题  但是文件类型 就不行了**
**我试试将 $content 格式化一下formdata**

![image](https://github.com/danni-cool/wechatbot-webhook/assets/75459234/073af7de-5b45-49e5-90fa-9a3bf65fdf8b)

**Comment by danni-cool** [comment]
你可以用一个postman，模拟发送接受端代码，看看代码content字段是文件时是否能解析

**Comment by bupojie888** [comment]
好的！ 我试试  
我这有ChatGpt 用他写代码很方便，需要的话可以给你搭建一个用哦！ 感觉你人不错！

**Comment by danni-cool** [comment]
不用啦，我日常也用chatgpt改代码

**Comment by bupojie888** [comment]
**嗯 好的 会用就好!! 我主要专研人工智能这方面！**
![image](https://github.com/danni-cool/wechatbot-webhook/assets/75459234/18dc86a7-bd59-46dc-9d1d-710487a5cb63)

**Comment by danni-cool** [comment]
可以多多交流，顺便一提你的content类型应该选择file而不是string

**Comment by bupojie888** [comment]
我选择的是参数值 是file的【目前发送过去提示是空】
我是不是应该接收参数应该写File啊 不应该是content
![image](https://github.com/danni-cool/wechatbot-webhook/assets/75459234/035bbf0d-c470-4940-ae50-8bfe8a287168)
![image](https://github.com/danni-cool/wechatbot-webhook/assets/75459234/c14f1b45-14df-4d22-b222-2c137d9708ae)

http://8.141.7.155:8080/receive_msg这个是我测试地址  你方便给我发一个消息吗

**Comment by danni-cool** [comment]
随手发了一个

**Comment by bupojie888** [comment]
好的  在发一下 刚才改东西了

**Comment by evilkong** [comment]
> **这个是我接收的参数, $content 文本是没问题 但是文件类型 就不行了** **我试试将 $content 格式化一下formdata**
> 
> ![image](https://private-user-images.githubusercontent.com/75459234/295426972-073af7de-5b45-49e5-90fa-9a3bf65fdf8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMzY3ODUsIm5iZiI6MTcwNTEzNjQ4NSwicGF0aCI6Ii83NTQ1OTIzNC8yOTU0MjY5NzItMDczYWY3ZGUtNWI0NS00OWU1LTkwZmEtOWEzYmY2NWZkZjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDA5MDEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZjY3YjM3N2E5NDQ4NGY4YzQzZDRjYTZmMzViNjRjNDk2MjdiNjA4YjQyMGQwMDBjYzk2N2ZmNGFjZmM2MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TyQCOjzIon51CgBFuFx-Ogav8r6xzlzEhUEUQgy6R-Q)

**php**
> $fileInfo = $_FILES["content"];
> move_uploaded_file($fileInfo['tmp_name'], ROOT.'/vxpic/'.$fileInfo['name']);
> 

**data**
Array
(
    [name] => 4340669986190094895.jpg
    [type] => image/jpeg
    [tmp_name] => /tmp/phpn8Ey2M
    [error] => 0
    [size] => 196993
)
