### ISSUE TITLE
macOS使用docker compose后误删除文件，重新下载后log文件时间错误，报错无法发送信息

### ISSUE THREAD

**Issue by JerryKongzzZ** [danni-cool/wechatbot-webhook#138]
报错信息：
Error: curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: application
curl: (3) URL rejected: Bad hostname
curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (3) unmatched brace in URL position 1:
{content:
 ^

使用python运行，使用docker compose利用本地log文件提取信息。
在log、yml文件删除后，输入github原指令wget -P ./wxbotWebhook......重新下载，log文件时间显示为第一次（第一题）下载日期（当前为第二天，日期应该加一天，但时间仍为当前的正确时间，很奇怪）
此为python中的curl语句：
curl_command = (
            f"curl --location 'http://localhost:3001/webhook/msg/v2' "
            f"--header 'Content-Type: application/json' "
            f"--data '{json_data}'"
        )
源文件在log文件夹删除之前可正常运行 
[app.2024-01-18.log](https://github.com/danni-cool/wechatbot-webhook/files/13980611/app.2024-01-18.log)
<img width="652" alt="Screenshot 2024-01-19 at 02 45 23" src="https://github.com/danni-cool/wechatbot-webhook/assets/112614111/9e58e7ac-d2cc-4d30-9f7a-23a62f3d9aae">
<img width="671" alt="Screenshot 2024-01-19 at 02 46 17" src="https://github.com/danni-cool/wechatbot-webhook/assets/112614111/4e6d2c7f-73d3-4761-aa40-1cd5934eed5c">

**Comment by danni-cool** [comment]
你这是没法解析 raw.githubusercontent.com，应该是DNS污染

本地映射下 ip 
151.101.76.133

**Comment by danni-cool** [comment]
也可以用这个命令

```bash
wget https://cdn.jsdelivr.net/gh/danni-cool/wechatbot-webhook@main/docker-compose.yml && docker-compose up
```

**Comment by danni-cool** [comment]
长时间无回复，关闭该问题
