### ISSUE TITLE
RECVD_MSG_API 的接口持续收到异常请求

### ISSUE THREAD

**Issue by leinad59** [danni-cool/wechatbot-webhook#140]
**提bug前先检查以下是否已经执行**

- [x] 我已更新了最新版本的代码
- [x] 我已经仔细地阅读了readme 文档
- [x] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [x] 我已经尝试搜索过历史关闭issue寻找可能的答案

**bug描述**

简短描述一下你在什么场景下遇到的问题

早上起来发现 RECVD_MSG_API 接入的 gpt token 都用完了，通过查看调用日志发现，从凌晨5点25开始间歇性地有大量请求。

**提供有用的信息**

提供任何代码片段/日志/输出/截图 以便于帮助快速定位问题

查看项目日志发现没有消息内容，只有 `starting fetching API: xxx` 和 `AssertionError: 3 == 0`：

<img width="857" alt="image" src="https://github.com/danni-cool/wechatbot-webhook/assets/60702016/3178b197-a66b-4595-b84e-2be1fb088619">

由接口逻辑推断，消息的 `type` 为 `text`，否则不会走到调用 gpt 请求的逻辑：

<img width="204" alt="image" src="https://github.com/danni-cool/wechatbot-webhook/assets/60702016/fb18af51-6823-4da6-a09a-7c84358c2e02">

日志中打印了 `source` 字段，内容为 `{"room":"","to":"","from":""}`

token 消耗记录显示，提示词的长度有两种，分别为 464 和 546：

<img width="217" alt="image" src="https://github.com/danni-cool/wechatbot-webhook/assets/60702016/09bb0ff3-6c15-4d20-81ac-b2ad42563fe4">

根据 gpt 的调用日志，猜测消息的 `content` 为以下两种：

<img width="814" alt="image" src="https://github.com/danni-cool/wechatbot-webhook/assets/60702016/551e1a96-bd3b-482b-b4c7-43280b06c875">

<img width="810" alt="image" src="https://github.com/danni-cool/wechatbot-webhook/assets/60702016/725af6f4-5f0e-422c-a0ee-bd2b1051a19f">

理论上来说，这种消息不应该发送到 RECVD_MSG_API，我也没有正确做出过滤。请问应该如何避免这个问题再次出现？

**Comment by leinad59** [comment]
<img width="860" alt="image" src="https://github.com/danni-cool/wechatbot-webhook/assets/60702016/aa2330b4-b558-41fc-a117-665912dd4920">

期间没有其他异常，是到凌晨5:25突然出问题的（日志需要+8h到北京时间）

**Comment by danni-cool** [comment]
无他，掉线了，但是wechaty 一直没登出所以一直报错，临时处理可以判断payload.isSystemEvent === false && type=== 'text'

**Comment by danni-cool** [comment]
后期考虑优化该结构，去除 payload.isSystemEvent, 增加 type 类型 _systemEvent，以便与其他结构区分

**Comment by leinad59** [comment]
> 无他，掉线了，但是wechaty 一直没登出所以一直报错，临时处理可以判断payload.isSystemEvent === false && type=== 'text'

看这里的朋友，记得确认文档中 isSystemEvent 的值是字符串的 '0'/'1' 还是布尔值 false/true，现状是 '0'/'1'

**Comment by danni-cool** [comment]
嗯，以文档为准，我看的源码
