### ISSUE TITLE
收不到企业微信账号发的消息

### ISSUE THREAD

**Issue by leinad59** [danni-cool/wechatbot-webhook#142]
**提bug前先检查以下是否已经执行**

- [x] 我已更新了最新版本的代码
- [x] 我已经仔细地阅读了readme 文档
- [x] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [x] 我已经尝试搜索过历史关闭issue寻找可能的答案

**bug描述**

简短描述一下你在什么场景下遇到的问题

场景：添加企业微信账号好友，重启容器，重新登录，企业微信账号给该账号发送消息
预期：容器收到消息并转发给自定义接口处理
实际：容器日志中没有企业微信账号发送的消息，也没有转发给自定义接口处理

**提供有用的信息**

提供任何代码片段/日志/输出/截图 以便于帮助快速定位问题

无

**Comment by danni-cool** [comment]
web协议不支持收企业消息

**Comment by qotu99** [comment]
那Window协议的版本支持收发企业微信的外部群里的消息吗？很期待这个功能

**Comment by danni-cool** [comment]
windows 协议最近刚跑通docker环境的启动，暂时没测试

**Comment by danni-cool** [comment]
> UOS 协议的微信。可以 sync_check 可以感知到 企微插件 的 新消息，但怎么获取到具体的消息内容，估计要等大佬取看看 UOS 支不支持了

uos 对企微支持性不好，没多大折腾空间，其中api不是针对企微场景设计的
