### ISSUE TITLE
扫码登录异常

### ISSUE THREAD

**Issue by i990099** [danni-cool/wechatbot-webhook#143]
**提bug前先检查以下是否已经执行**

- [X] 我已更新了最新版本的代码
- [X] 我已经仔细地阅读了readme 文档
- [X] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [X] 我已经尝试搜索过历史关闭issue寻找可能的答案

**bug描述**

简短描述一下你在什么场景下遇到的问题
扫码登录时，并没有登录成功，日志打印如下：
wxBotWebhook  | [2024-01-25T08:58:46.470] [ERROR] -
wxBotWebhook  | AssertionError: 1 == 0
请问这种情况如何解决，我重启过docker，还是这样
**提供有用的信息**

提供任何代码片段/日志/输出/截图 以便于帮助快速定位问题
![image](https://github.com/danni-cool/wechatbot-webhook/assets/29566178/d3ff3aec-ed57-4278-9ece-dcc7d589a8b4)

**Comment by danni-cool** [comment]
FAQ 第一条参照下

**Comment by i990099** [comment]
谢谢，已解决，是没有实名认证导致的
