### ISSUE TITLE
npm安装依赖失败，麻烦指导一下谢谢

### ISSUE THREAD

**Issue by lovecodeyou** [danni-cool/wechatbot-webhook#145]
![image](https://github.com/danni-cool/wechatbot-webhook/assets/38997988/c71424d0-8b17-48b4-ba6b-3f574f34abed)

![image](https://github.com/danni-cool/wechatbot-webhook/assets/38997988/3d2a5afa-5417-481d-af07-9ae5de498643)

**Comment by danni-cool** [comment]
用pnpm

**Comment by lovecodeyou** [comment]
![image](https://github.com/danni-cool/wechatbot-webhook/assets/38997988/fcb903e6-6822-491f-99ed-0e2b45979dc7)


依然不行

**Comment by lovecodeyou** [comment]
有具体的npm node版本的要求吗，或者可以告知一下你们现在开发这个应用所使用 node npm版本以及依赖镜像是用的哪里的

**Comment by leinad59** [comment]
用npm start启动
