### ISSUE TITLE
pnpm安装依赖失败，麻烦指导一下谢谢

### ISSUE THREAD

**Issue by lovecodeyou** [danni-cool/wechatbot-webhook#146]
https://github.com/danni-cool/wechatbot-webhook/issues/145

**Comment by danni-cool** [comment]
.env 文件，port设置了吗

**Comment by leinad59** [comment]
请参照项目中的 .env.example 文件新建一份 .env 文件，经自测可行

**Comment by leinad59** [comment]
抱歉，之前回答有误，在package.json中已经有了prestart脚本用来创建.env文件。
但pnpm start不支持自动执行prestart脚本，你可以使用npm start启动项目。或先手动执行一次pnpm prestart。

**Comment by qianqiuZjx** [comment]
部署成功了吗
