### ISSUE TITLE
自己重新构建的项目Module not found: Can't resolve 'etcd3'

### ISSUE THREAD

**Issue by lyworry** [danni-cool/wechatbot-webhook#148]
我自己用nextjs构建了项目，npm i了wechat4u和wechaty，但是在
`const { WechatyBuilder } = require('wechaty')
const bot =WechatyBuilder.build()`
时，会缺少包，etcd3，`Module not found: Can't resolve 'etcd3'`，在执行你的项目的时候却不会（wechat4u和wehcahty版本和你的一样）。我看你的项目里node_modules里也没有etcd3这个包，但你的项目执行却不会报错，似乎没有执行到这一步，但我们的入口方法是一样的，我不理解，不知道为题在哪里

**Comment by danni-cool** [comment]
node version?

**Comment by lyworry** [comment]
v20.11.0

**Comment by danni-cool** [comment]
downgrade to 18

**Comment by lyworry** [comment]
但是clone你的项目，运行并没有问题....

**Comment by danni-cool** [comment]
pnpm 管理了package里定义的node版本貌似，期待你的研究结论
