### ISSUE TITLE
接收消息报错：用文档的测试用例可以调通，但是部署时报错

### ISSUE THREAD

**Issue by swfinale** [danni-cool/wechatbot-webhook#154]
**提bug前先检查以下是否已经执行**

- [ √] 我已更新了最新版本的代码
- [ √] 我已经仔细地阅读了readme 文档
- [ √] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [ √] 我已经尝试搜索过历史关闭issue寻找可能的答案

**bug描述**
设置自己编写的接口作为参数传入，应用启动成功，但是接收消息报错：Error occurred when trying to send Data to RecvdApi FetchError: request to http://localhost:8080/public/receive failed, reason: connect ECONNREFUSED 127.0.0.1:8080
<img width="1389" alt="image" src="https://github.com/danni-cool/wechatbot-webhook/assets/38309171/da73dfbe-64e6-467d-95e8-06505d753687">

用文档里的测试用例可以成功返回
<img width="773" alt="image" src="https://github.com/danni-cool/wechatbot-webhook/assets/38309171/7a917a6e-33c5-44fc-bfee-c3d4beb03d1c">

接口编写如下：
<img width="838" alt="image" src="https://github.com/danni-cool/wechatbot-webhook/assets/38309171/c842987b-0b85-4449-9759-ab8cf16ad73e">

**提供有用的信息**

提供任何代码片段/日志/输出/截图 以便于帮助快速定位问题

**Comment by leinad59** [comment]
可能是容器内外网络不通，尝试启动容器时使用–net=host

**Comment by swfinale** [comment]
确认是容器网络不通，用host模式启动解决

**Comment by swfinale** [comment]
确认是容器网络不通，用host模式启动解决

**Comment by leinad59** [comment]
@danni-cool 可以加到FAQ😄

**Comment by yingling686** [comment]
我遇到了同样的问题，但是目前以host模式启动也没有解决掉这个情况，能不能帮我解释一下子 @danni-cool
