### ISSUE TITLE
目前别人发来好友请求，收不到post请求，而文字什么的其他类型都可以

### ISSUE THREAD

**Issue by cultureship** [danni-cool/wechatbot-webhook#155]
**提bug前先检查以下是否已经执行**

- [ ] 我已更新了最新版本的代码
- [x] 我已经仔细地阅读了readme 文档
- [x] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [ ] 我已经尝试搜索过历史关闭issue寻找可能的答案

**bug描述**

简短描述一下你在什么场景下遇到的问题

**提供有用的信息**

提供任何代码片段/日志/输出/截图 以便于帮助快速定位问题

**Comment by danni-cool** [comment]
已复线，正在修复
