### ISSUE TITLE
添加wechaty-puppet以模拟UOS客户端

### ISSUE THREAD

**Issue by Lynnette177** [danni-cool/wechatbot-webhook#164]
由于网页微信很容易出现 安全问题考虑禁止登录 小号非常容易就这样废了。目前的方案是模拟UOS的登录请求头。Wechaty本身已经支持了，只是放到了WECHATY-PUPPET-WECHAT这个puppet。我尝试在arm64镜像内进行安装，但由于树莓派3性能太拉跨了npm需要装太长太长时间，希望作者能帮忙npm install一下，这样登不上网页微信的（包括海外微信）都可以被模拟成UOS客户端登录了。
https://wechaty.js.org/2021/04/13/wechaty-uos-web/
https://github.com/wechaty/puppet-wechat?tab=readme-ov-file
只要NPM install一下就可以 万分感谢

**Comment by danni-cool** [comment]
目前默认的wechaty-puppet-wechat4u 就是模拟 uos的请求，基于http api，所以才可以实现网页微信不能用，但是登录wechaty是可行的，至于替换成wechaty-puppet-wechat 是一个angular 封装的实现的方案没有变化，具体有哪些收益呢？

**Comment by Lynnette177** [comment]
> 目前默认的wechaty-puppet-wechat4u 就是模拟 uos的请求，基于http api，解决了微信号虽然网页微信不能用，但是登录本项目是可行的，至于替换成wechaty-puppet-wechat 是一个angular 封装的，底层实现的方案没有变化，具体有哪些收益呢？

不好意思，我不知道目前有这个puppet。但是目前似乎没有模拟uos请求，因为手机端显示是网页版在线（如果是uos会显示客户端在线），今天我的微信号网页版上不去，这边wechaty也上不去了，是不是要改一下init.js里面对puppet的默认设置，我看wechaty的文档，默认uos是关的。

**Comment by Lynnette177** [comment]
解决了，我在docker-compose.yml内添加了 - WECHATY_PUPPET=wechaty-puppet-wechat4u
就可以登录了 谢谢您

**Comment by danni-cool** [comment]
官方目前已经推荐使用这个 wechaty-puppet-wechat4u ， wechaty-puppet-wechat 好像已经废弃了，刚测试跑不起来。

- WECHATY_PUPPET=wechaty-puppet-wechat4u 应该是不用加的，应该是你的微信刚解封
