### ISSUE TITLE
所有接口都添加Token的验证

### ISSUE THREAD

**Issue by jiusun** [danni-cool/wechatbot-webhook#166]
**提出问题的背景**

现在Token仅在调用 其他API 时才需要校验，因为机器人的接口暴露到公网了，出于安全考虑，推消息是不是也应该加上Token的检验？

**描述下你期望的方案**

推消息接口应该要求携带Token，并进行校验。

**Comment by danni-cool** [comment]
确实可以加一下，等发布吧
