### ISSUE TITLE
登录成功后报如下错误立马退出登录

### ISSUE THREAD

**Issue by Eternallyl** [danni-cool/wechatbot-webhook#167]
![image](https://github.com/danni-cool/wechatbot-webhook/assets/59507559/3f571c49-7955-4eba-9832-f1d2fa71c0ae)

**Comment by Cassius0924** [comment]
遇到过，我当时是切换了节点解决的

**Comment by Eternallyl** [comment]
> 遇到过，我当时是切换了节点解决的

换一台服务器吗？

**Comment by danni-cool** [comment]
重启有改善么

**Comment by Eternallyl** [comment]
> 重启有改善么

没有，还是登陆成功后报错立马掉线

**Comment by Cassius0924** [comment]
也许是网络环境问题，可以试着重启服务器

**Comment by danni-cool** [comment]
> > 重启有改善么
> 
> 没有，还是登陆成功后报错立马掉线

换帐号呢？有无可能是账号被封了？

**Comment by Eternallyl** [comment]
> > > 重启有改善么
> > 
> > 
> > 没有，还是登陆成功后报错立马掉线
> 
> 换帐号呢？有无可能是账号被封了？

有可能，我试一下

**Comment by leinad59** [comment]
遇到过多次

1. 账号没被封
2. 重启容器没用
3. 试了重启服务器，恢复了
4. 刚掉线后短时间内再登录会这样
5. 过一段时间再登就可以了

**Comment by danni-cool** [comment]
@leinad59 如果重启容器无用，需要重启服务器级别的，那应该是和项目本身没关系了，大概率是微信服务器这段时间不让你登录吧

**Comment by Eternallyl** [comment]
> 遇到过多次
> 
> 1. 账号没被封
> 2. 重启容器没用
> 3. 试了重启服务器，恢复了
> 4. 刚掉线后短时间内再登录会这样
> 5. 过一段时间再登就可以了

解决了 感谢，昨天充了一笔话费，今天重启下服务器就能登录了

**Comment by leinad59** [comment]
> 之前用的好好的，今天突然也遇到这个问题了，冲了个话费，观望一下

@ShiFangJuMie 你们说的充话费指的是什么？:-)

**Comment by danni-cool** [comment]
各位充了话费是暗号吗？？

**Comment by Daydaylw3** [comment]
我遇到这个问题两三次了吧，没有资金流动，就是等个半天一天的就可以登录了
