### ISSUE TITLE
接收的地理位置：是否可以接收到坐标？

### ISSUE THREAD

**Issue by bupojie888** [danni-cool/wechatbot-webhook#175]

**Comment by bupojie888** [comment]
没有坐标,是否可以把显示的文字,显示全. 
目前只显示了小字的地理位置信息！
![image](https://github.com/danni-cool/wechatbot-webhook/assets/75459234/9b2ad1ae-30ad-476e-82f9-f6dceb5652b2)

接收到的：
吉林省长春市南关区大经路1785号(南关地铁站B口步行470米):

**Comment by danni-cool** [comment]
web 协议目前不支持
