### ISSUE TITLE
能不能不用昵称发送消息,因为有可能重名？这样就没办法绑定会员了？

### ISSUE THREAD

**Issue by bupojie888** [danni-cool/wechatbot-webhook#177]

**Comment by Cassius0924** [comment]
可以用备注发送，建议提 issue 前先查 [README](https://github.com/danni-cool/wechatbot-webhook/blob/main/README.md) 和 [FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)

**Comment by danni-cool** [comment]
web底层不支持，不过欢迎PR
