### ISSUE TITLE
请问作者提交github的提交说明使用什么工具生成的吗？

### ISSUE THREAD

**Issue by firefoxmmx2** [danni-cool/wechatbot-webhook#178]
如题，提交说明的格式很有趣且清晰。 请问使用了什么工具提交的吗

**Comment by danni-cool** [comment]
需要用到的工具：
- 代码提交：https://github.com/streamich/git-cz
- github action: [GoogleCloudPlatform/release-please-action@v3](https://github.com/google-github-actions/release-please-action)

原理：
1. 平时写代码提交使用git-cz生成带emoji的记录（注意干净整洁的commit提交）
2. 功能迭代后 github提交pr 到 main分支 
3. 在main 分支定义一个 github action： https://github.com/danni-cool/wechatbot-webhook/blob/main/.github/workflows/release.yml
4. 等待 github action 生成发布release pr （这个是自动生成的release pr https://github.com/danni-cool/wechatbot-webhook/pull/170）
5. 合并 release pr 并且发布包（自动完成）

**Comment by firefoxmmx2** [comment]
谢谢
