### ISSUE TITLE
{"success":false,"message":"Unauthorized: Access is denied due to invalid credentials."}

### ISSUE THREAD

**Issue by hpyer2016** [danni-cool/wechatbot-webhook#182]
请问大佬，发送消息失败{"success":false,"message":"Unauthorized: Access is denied due to invalid credentials."}，扫码登录提示已经成功
{
    "success": true,
    "message": "Contact<XXX>is already login"
}

**Comment by Cassius0924** [comment]
请展示一下你的请求URL，新版的URL需要带上`token`参数。
```
http://localhost:3001/webhook/msg/v2?token=[YOUR_PERSONAL_TOKEN]
```

**Comment by l137295** [comment]
> 请展示一下你的请求URL，新版的URL需要带上`token`参数。
> 
> ```
> http://localhost:3001/webhook/msg/v2?token=[YOUR_PERSONAL_TOKEN]
> ```

请问，我登录时，浏览器显示：{ "success": false, "message": "Unauthorized: Access is denied due to invalid credentials." } ，是不是一个问题呢？
