### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by hhhhhge** [danni-cool/wechatbot-webhook#185]
**提bug前先检查以下是否已经执行**

- [x] 我已更新了最新版本的代码
- [x] 我已经仔细地阅读了readme 文档
- [ ] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [ ] 我已经尝试搜索过历史关闭issue寻找可能的答案

**bug描述**

登录时遇到的

**提供有用的信息**

AssertionError: 1 == 0

**Comment by releee** [comment]
这个情况通常是没有实名

**Comment by hhhhhge** [comment]
话说为什么一定要实名
