### ISSUE TITLE
文件后缀名不能识别

### ISSUE THREAD

**Issue by hhhhhge** [danni-cool/wechatbot-webhook#186]
**提bug前先检查以下是否已经执行**

- [x] 我已更新了最新版本的代码
- [x] 我已经仔细地阅读了readme 文档
- [x] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [x] 我已经尝试搜索过历史关闭issue寻找可能的答案

**bug描述**

不能识别文件类型，原来是png的，用py写的代码

**提供有用的信息**
![c8050a89a172ad263963c4f575d8d520](https://github.com/danni-cool/wechatbot-webhook/assets/102860110/415da751-214e-4925-9365-0d163eb8c249)

**Comment by Cassius0924** [comment]
#184

**Comment by danni-cool** [comment]
和微信规则一样，你要识别成啥，自己加后缀名。

**Comment by hhhhhge** [comment]
可不可以加上参数来指定

**Comment by danni-cool** [comment]
可以，目前有一个pr在进行中
