### ISSUE TITLE
群备注问题

### ISSUE THREAD

**Issue by coder-yzx** [danni-cool/wechatbot-webhook#189]
**提出问题的背景**
发送群消息时，有的群昵称带有特殊字符，导致消息发送失败。
例如：
🌹 coder1⃣ 群
**描述下你期望的方案**
支持群备注

**Comment by Cassius0924** [comment]
web协议不支持群备注。

我测试下，带特殊字符的群也是可以发消息的。

**Comment by coder-yzx** [comment]
![image](https://github.com/danni-cool/wechatbot-webhook/assets/63107682/fe6a360e-68af-4fc4-87e7-b054c31d5d4f)

**Comment by coder-yzx** [comment]
用docker部署的服务，采用post发送json数据，是不是因为解码的原因？那您是如何发送成功的？

curl --location --request POST 'http://localhost:3002/webhook/msg?token=wxbot' \
--header 'Content-Type: application/json' \
--data-raw '{
    "to": "🌹 信息1⃣ 群️",
    "type": "fileUrl",
    "content": "https://samplelib.com/lib/preview/mp3/sample-3s.mp3",
    "isRoom": true
}'

**Comment by Cassius0924** [comment]
尝试一下重新登录机器人。

**Comment by coder-yzx** [comment]
可以了，日志里复制那个群的名称就可以发送了
