### ISSUE TITLE
期望通过uuid发送提前准备好的数据

### ISSUE THREAD

**Issue by danni-cool** [danni-cool/wechatbot-webhook#190]
> > 不是不是，其实就是先把带有名字的图片缓存一下而已
> 
> 大图避免二次下载是吗

是这样的，我详细的说一下
我先post一个提前备好的图片数据并在json里包含文件类型等信息，然后我可以拿一个方式比如uuid这样的去把这个图片发送出去

_Originally posted by @hhhhhge in https://github.com/danni-cool/wechatbot-webhook/issues/184#issuecomment-2004109919_

**Comment by hhhhhge** [comment]
大佬可以实现吗

**Comment by hhhhhge** [comment]
> 大佬可以实现吗

在原有的api上加一个新接口用于发送文件和json格式的文件信息，并且在原来的发送消息的接口上增加一种类型就行

**Comment by Cassius0924** [comment]
> 大图避免二次下载是吗

对于这个建议在应用层实现，先下载作为缓存，再使用本地文件推送方式上传。

而且一般来说，你不会对一个图片或文件进行多次发送操作，如果需要发给多个人，可以选择群发。

将文件保存在服务端，每次发送文件都会占用存储空间，所以服务端还必须实现对上传的文件的生命周期管理，定时清理文件，这无疑会使代码更复杂。

如果一个文件被服务端定时删除了，如果应用层还尝试使用这个文件的UUID进行发送操作，将会失败，失败后，应用层还需要写另外的代码逻辑进行处理这种情况。

总的来说，我觉得没必要。

**Comment by danni-cool** [comment]
结论是还是建议基于本项目再外挂一个图片服务，此话题不再讨论
