### ISSUE TITLE
本地http资源添加query参数$alias别名无法访问到文件

### ISSUE THREAD

**Issue by hhhhhge** [danni-cool/wechatbot-webhook#193]
⚠️不按照以下格式创建的issue将不会获得回复⚠️ 

## 提bug前先检查以下是否已经执行

- [x] 我已更新了最新版本的代码
- [x] 我已经仔细地阅读了readme 文档
- [x] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [x] 我已经尝试搜索过历史关闭issue寻找可能的答案

## bug描述
我在本地搭建一个图片服务器上传图片，修改为新版本添加参数后我的服务器不能用了

所以请按以下格式描述问题：

- **场景**：
- **操作**：
- **表现**：

## 提供有用的信息
- 目前使用的版本号：（很可能最新版本已经修复了）
![image](https://github.com/danni-cool/wechatbot-webhook/assets/102860110/1d71aa4d-fa51-4e82-a9b9-9458e0853d7c)
![image](https://github.com/danni-cool/wechatbot-webhook/assets/102860110/744c3f34-303e-423a-bd0b-9246cef638b8)

**Comment by hhhhhge** [comment]
他怎么就还把他传递出去了

**Comment by hhhhhge** [comment]
> 他怎么就还把他传递出去了

其他的网站也这样

**Comment by danni-cool** [comment]
本地服务器文件无法获取和你的本地服务器处理 query 参数的策略有关，请确保 `http://127.0.0.1:5000/read_file?$alias=upload.png` 可以在你本地浏览器里可以访问到该资源，否则请修改你python http 服务器对该资源的处理规则

**Comment by hhhhhge** [comment]
行吧，为什么不是把这个参数去掉并请求

**Comment by danni-cool** [comment]
未来可能考虑优化，目前能用就行
