### ISSUE TITLE
发送图片出现错误断言的异常

### ISSUE THREAD

**Issue by kiinWizard** [danni-cool/wechatbot-webhook#194]
⚠️不按照以下格式创建的issue将不会获得回复⚠️ 

## 提bug前先检查以下是否已经执行

- [x] 我已更新了最新版本的代码
- [x] 我已经仔细地阅读了readme 文档
- [x] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [x] 我已经尝试搜索过历史关闭issue寻找可能的答案

## bug描述
发送图片失败，之前正常使用，突然开始发送失败，检测图片无违规问题

所以请按以下格式描述问题：

- **场景**：
- sd api 发送图片
- **操作**：
- 测试sdapi发送图片过程中出现，并且在postman 中复现
- **表现**：
webhook/msg 发送图片状态200 但是发送失败
## 提供有用的信息
- 目前使用的版本号：docker 镜像3月2号的latest（很可能最新版本已经修复了）
- 提供任何代码片段/日志/输出/截图 以便于帮助快速定位问题
- {
    "success": false,
    "message": "Message sent failed",
    "error": {
        "generatedMessage": true,
        "code": "ERR_ASSERTION",
        "actual": 1205,
        "expected": 0,
        "operator": "==",
        "response": {
            "status": 200,
            "statusText": "OK",
            "headers": {
                "connection": "close",
                "content-type": "text/plain",
                "strict-transport-security": "max-age=31536000",
                "content-length": "79"
            },
            "config": {
                "transitional": {
                    "silentJSONParsing": true,
                    "forcedJSONParsing": true,
                    "clarifyTimeoutError": false
                },
                "adapter": [
                    "xhr",
                    "http"
                ],
                "transformRequest": [
                    null
                ],
                "transformResponse": [
                    null
                ],
                "timeout": 60000,
                "xsrfCookieName": "XSRF-TOKEN",
                "xsrfHeaderName": "X-XSRF-TOKEN",
                "maxContentLength": -1,
                "maxBodyLength": -1,
                "env": {},
                "headers": {
                    "Accept": "application/json, text/plain, */*",
                    "Content-Type": "application/json",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
                    "connection": "close",
                    "cookie": "pgv_pvi=1753609817610049300; pgv_si=s1030574638116371300; wxuin=2853955611; wxsid=raJByXktC8Tg2K0O; wxloadtime=1711037546_expired; mm_lang=zh-CN; webwx_data_ticket=gSdyHpwnM8ydNEHqbbSmLS1b; webwxuvid=0309858f185314733b9ca7e316a2d4a8fe906280488538c56921488d84466b44841b2d0897ed9f79b86124650ac45e51; webwx_auth_ticket=CIsBEKPhxOkIGoABWL+jVcAu64jLm9X5lP8Ok4HVNXzVoo7e22hCiXVTVKTt/IKxkS92xUu1qdLTtgGtNrOeNLp/w83Tkqdv68Rm77hriNkrWjNL7eryX59u/SkXtjAOteBYorTkPhdkaPreQdLwQiqr0acgtOvcXFrZP+DyV5PTi57GZVCqCRVNiEU=; wxpluginkey=1711116003",
                    "Content-Length": "1001",
                    "Accept-Encoding": "gzip, compress, deflate, br"
                },
                "Cookie": {
                    "pgv_pvi": "2151587526396539100",
                    "pgv_si": "s535490345077726600",
                    "wxuin": "2853955611",
                    "wxsid": "raJByXktC8Tg2K0O",
                    "wxloadtime": "1711037546",
                    "mm_lang": "zh-CN",
                    "webwx_data_ticket": "gSdyHpwnM8ydNEHqbbSmLS1b",
                    "webwxuvid": "0309858f185314733b9ca7e316a2d4a8fe906280488538c56921488d84466b44841b2d0897ed9f79b86124650ac45e51",
                    "webwx_auth_ticket": "CIsBEKPhxOkIGoABWL+jVcAu64jLm9X5lP8Ok4HVNXzVoo7e22hCiXVTVKTt/IKxkS92xUu1qdLTtgGtNrOeNLp/w83Tkqdv68Rm77hriNkrWjNL7eryX59u/SkXtjAOteBYorTkPhdkaPreQdLwQiqr0acgtOvcXFrZP+DyV5PTi57GZVCqCRVNiEU="
                },
                "httpAgent": false,
                "httpsAgent": false,
                "method": "post",
                "url": "https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxsendmsgimg",
                "params": {
                    "pass_ticket": "ZXOMa%2BgEGBXMO7ubZeY0SRh4xevTP7b18FnP6R%2B7sQ0%2B8QDBeqMtUMlr7%2FbPnF8VH1DY1PYH3KUOz%2B4Hpzdp0g%3D%3D",
                    "fun": "async",
                    "f": "json",
                    "lang": "zh_CN"
                },
                "data": "{\"BaseRequest\":{\"Uin\":2853955611,\"Sid\":\"raJByXktC8Tg2K0O\",\"Skey\":\"@crypt_74e74dc5_3e9cbdd5ef9e4e9d1152b8fda1c72470\",\"DeviceID\":\"e609554000223994\"},\"Scene\":0,\"Msg\":{\"Type\":3,\"MediaId\":\"@crypt_54ad2c8a_7491b3557f50fbfb53160388fe7a51450792079060aacdeac8e14f887c6dda6be5269f854436289c19048806c3a28804c8ffbd88155c5184baf3ae674b14966ddf01ed17e826f65bdfbf695d05daf1dab7153c38a4eead9164ae81e5a9b8eef0c51dcdbce98559e8e052dba6f75b7356305f16f05e2ea1461a9ed6cf860b604e1075d5c93c6d8d16b8b8df5f9a7e91f8919db72ec3b8bff862880b2a1fb0b13dd89154cd1761d9cebcd304d189fd758094467cb3010a329345939d249f2c7179774d6560fe169f85447ce783f4d54825c9214a4426848759bf8e6c2086c33efcf09e9bd9c6a7e28d343c8fb606cca965db5ffd3f1e0e25d79190fb01f2df8f409f6e893c8b8962c5a2bc8f536808fcfda9b0195f8aefbaeffa93ced776299bf2\",\"FromUserName\":\"@0ca62394974c99bcf75d07ee10447350170a6bc8f18e1d0f51102b41d75f7612\",\"ToUserName\":\"@959009a11ea868cedb9c675bbe0ec0be4a672d3d54590a6bafa62bb5cc891021\",\"LocalID\":1711123063606000,\"ClientMsgId\":1711123063606000}}"
            },
            "data": {
                "BaseResponse": {
                    "Ret": 1205,
                    "ErrMsg": ""
                },
                "MsgID": "",
                "LocalID": ""
            }
        },
        "tips": "发送图片失败"
    }
}

**Comment by danni-cool** [comment]
应该是掉线了，发送失败前日志没有其他错误吗

**Comment by DuskXi** [comment]
我这边也有这种情况，是群友在高强度让机器人发图片以后出现的，和IP没关系，换个号就可以，但是现在不知道被限制的号会不会一直被限制
