### ISSUE TITLE
web微信支持语音消息吗

### ISSUE THREAD

**Issue by kiinWizard** [danni-cool/wechatbot-webhook#197]
⚠️不按照以下格式创建的issue将不会获得回复⚠️ 

**提出问题的背景**

有没有可能支持下发送语音，这样走gpt 文本生成之后可以直接走tts，处理发送语音。

**描述下你期望的方案**

希望支持发送语音消息吗，还是说web不兼容

**其他信息**
提供代码/截图/日志/输出等必要文件辅助描述

**Comment by danni-cool** [comment]
勤读readme
