### ISSUE TITLE
头像

### ISSUE THREAD

**Issue by EashShow** [danni-cool/wechatbot-webhook#198]
⚠️不按照以下格式创建的issue将不会获得回复⚠️ 

## 提bug前先检查以下是否已经执行

- [x] 我已更新了最新版本的代码
- [x] 我已经仔细地阅读了readme 文档
- [x] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [x] 我已经尝试搜索过历史关闭issue寻找可能的答案

## bug描述
这也不叫Bug吧

所以请按以下格式描述问题：

- **场景**：
我希望能够获取微信用户头像
- **操作**：
接口返回信息Avatar中只有一个相对地址，我尝试将 https://wx.qq.com 拼接上去，发现也是获取不了头像
- **表现**：
获取不了头像

## 提供有用的信息
- 目前使用的版本号：最新版本
- 提供任何代码片段/日志/输出/截图 以便于帮助快速定位问题
Avatar中返回的字符串是这样的：/cgi-bin/mmwebwx-bin/webwxgeticon?XXXXXXXXXXX

**Comment by danni-cool** [comment]
获取头像需要当前登陆状态的cookie, 登出获取不了，后续可能以返回一个你服务的地址+完整拼接代理获取

**Comment by EashShow** [comment]
或者另外开放一个获取头像的API，绕开Cookie，直接通过Docker去获取
