### ISSUE TITLE
配合 token=[YOUR_PERSONAL_TOKEN] 解密的方式是？

### ISSUE THREAD

**Issue by coder-yzx** [danni-cool/wechatbot-webhook#203]
## bug描述
//请配合 token=[YOUR_PERSONAL_TOKEN] 解密
请问，采用的什么样的解密方式呢？

- **场景**：
- 接受消息的接口，查看消息内容
- **操作**：
- **表现**：
- ` # 解析请求中的表单数据
        type = request.POST.get('type')
        content = request.POST.get('content')
        source = request.POST.get('source')
        is_mentioned = request.POST.get('isMentioned')
        is_msg_from_self = request.POST.get('isMentioned')
        isSystemEvent = request.POST.get('isSystemEvent')
        print('type:', type)
        print('content:', content)`
print('source:', source)
UnicodeEncodeError: 'gbk' codec can't encode character '\u2747' in position 1796: illegal multibyte sequence

**Comment by coder-yzx** [comment]
后端用的django，前端是docker部署的。从docker日志上能看到请求内容，那么
配合 token=[YOUR_PERSONAL_TOKEN] 解密是什么意思呢？

**Comment by danni-cool** [comment]
就是avatar地址默认是要拼接token参数才能访问
https://github.com/wechatbotKit/wechatbot-webhook?tab=readme-ov-file#33-%E8%8E%B7%E5%8F%96%E9%9D%99%E6%80%81%E8%B5%84%E6%BA%90%E6%8E%A5%E5%8F%A3
