### ISSUE TITLE
稳定性相对于wechaty如何？

### ISSUE THREAD

**Issue by jingjining1** [danni-cool/wechatbot-webhook#204]
⚠️不按照以下格式创建的issue将不会获得回复⚠️ 

## 提bug前先检查以下是否已经执行

- [x] 我已更新了最新版本的代码
- [x] 我已经仔细地阅读了readme 文档
- [x] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [x] 我已经尝试搜索过历史关闭issue寻找可能的答案

## bug描述
有时候一句话问题并不知道在描述什么

所以请按以下格式描述问题：

- **场景**：
- **操作**：
- **表现**：

## 提供有用的信息
- 目前使用的版本号：（很可能最新版本已经修复了）
- 提供任何代码片段/日志/输出/截图 以便于帮助快速定位问题

**Comment by jingjining1** [comment]
稳定性相对于wechaty如何？

**Comment by danni-cool** [comment]
除了web协议2天掉一次，能稳定的都给你优化了
