### ISSUE TITLE
接收消息后，总是会多调用一次收消息的api

### ISSUE THREAD

**Issue by a877429929** [danni-cool/wechatbot-webhook#205]
⚠️不按照以下格式创建的issue将不会获得回复⚠️ 

## 提bug前先检查以下是否已经执行

- [ x ] 我已更新了最新版本的代码
- [ x ] 我已经仔细地阅读了readme 文档
- [ x ] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [ x ] 我已经尝试搜索过历史关闭issue寻找可能的答案

## bug描述
有时候一句话问题并不知道在描述什么

所以请按以下格式描述问题：

- **场景**：
- **操作**：
- **表现**：
微信收到消息后，总是会多收到一个unknown的消息，然后调用了一次api

unknown消息体
{"event":"notifyOfRecvdApiPushMsg","recvdApiReplyNotify":{"success":true,"task":{"successCount":1,"totalCount":1,"failedCount":0,"reject":[],"sentFailed":[],"notFound":[]},"message":"Message sent successfully","status":200}}
## 提供有用的信息
- 目前使用的版本号：最新版本（很可能最新版本已经修复了）
- 提供任何代码片段/日志/输出/截图 以便于帮助快速定位问题

**Comment by danni-cool** [comment]
你用了“快捷回复”功能，多一次调用是通知你api这条消息发送成功没。但是返回的为啥是 unknown 类型消息？不应该是 `system_event_push_notify ` ？

```
source:{"room":{},"to":{},"from":{}}
isSystemEvent:1
isMentioned:0
isMsgFromSelf:0
type:system_event_push_notify
content:{"event":"notifyOfRecvdApiPushMsg","recvdApiReplyNotify":{"success":true,"task":{"successCount":2,"totalCount":2,"failedCount":0,"reject":[],"sentFailed":[],"notFound":[]},"message":"Message sent successfully","status":200}}
```
