### ISSUE TITLE
小白出现的问题，希望得到回复

### ISSUE THREAD

**Issue by jingjining1** [danni-cool/wechatbot-webhook#206]
⚠️不按照以下格式创建的issue将不会获得回复⚠️ 

## 提bug前先检查以下是否已经执行

- [x] 我已更新了最新版本的代码
- [x] 我已经仔细地阅读了readme 文档
- [x] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [x] 我已经尝试搜索过历史关闭issue寻找可能的答案

## bug描述
有时候一句话问题并不知道在描述什么

所以请按以下格式描述问题：

- **场景**：
- **操作**：
- **表现**：

## 提供有用的信息
- 目前使用的版本号：（很可能最新版本已经修复了）
- 提供任何代码片段/日志/输出/截图 以便于帮助快速定位问题
发动信息搞定了，接收信息应该从哪里着手啊，这个API的URL研究了好几个小时，不知道从哪里下手，希望能提供点思路，项目的案例也在postman上测试了，也通过了不了；谢谢

**Comment by bwnjnOEI** [comment]
我能理解你的心情。之前我是小小小白一点经验都没有，前/后端以及`postman`是什么都不清楚，只会`python`和`latex`(如果它也算一门语言)，通过和AI聊天学习我现在成功部署了接收消息的服务端并接入了LLM。关于你说的postman上测试了过不了问题，接收API的这个返回值是你在接收消息服务中自己return的，我是用`python`中的`flask`写的，你把RECVD_MSG_API=https://example.com/your/url设置好后，一旦[wechatbot-webhook](https://github.com/danni-cool/wechatbot-webhook)服务启动并登录，它都会向这个地址发送请求，你需要，比如：用`flask`框架，写个接收服务解析传来的`json`以及自己对消息处理的逻辑。以上就是我的思路，我也不知道对不对正不正宗，反正work了😊

**Comment by jingjining1** [comment]
感谢回复，研究了2天，终于解决了，现在已经能正常运行了，就是还不知道图片能不能发送出去？type需不需要做说明，以前用base64发送到企业微信内部群的

**Comment by jingjining1** [comment]
这个，对文本内容进行换行或者格式调整，为什么信息就发送不出去了，说是body的json错误
