### ISSUE TITLE
读取文件并发送提示错误not a valid json

### ISSUE THREAD

**Issue by Pai-Po** [danni-cool/wechatbot-webhook#207]
⚠️不按照以下格式创建的issue将不会获得回复⚠️ 

## 提bug前先检查以下是否已经执行

- [x] 我已更新了最新版本的代码
- [x] 我已经仔细地阅读了readme 文档
- [x] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [x] 我已经尝试搜索过历史关闭issue寻找可能的答案

## bug描述
我在尝试读取一个文件内容并发送，但是更新了最新版本后，出现了这个问题，总是提示request body is not a valid json；我尝试添加了头参数 -H 'Content-Type: multipart/form-data'，还是同样的错误提示。

所以请按以下格式描述问题：

- **场景**：
- 读取文件内容并发送
- **操作**：
- `curl --location --request POST 'http://localhost:3001/webhook/msg/v2?token=*********' --form 'to={"alias":"Hoster"}' --form content=@"$HOME/demo.jpg" `
- **表现**：
{"success":false,"message":"request body is not a valid json! checkout please."}

## 提供有用的信息
- 目前使用的版本号：重新拉取了最新版本
- 提供任何代码片段/日志/输出/截图 以便于帮助快速定位问题

**Comment by danni-cool** [comment]
建议使用postman等去处理，受打curl 难免出现问题，以下是刚用postman 验证过的导出的curl格式

```
curl --location 'http://localhost:3001/webhook/msg?token=FncnVI3ykEy9' \
--form 'to="{alias: \"小号\"}"' \
--form 'content=@"/Users/daniel/Downloads/Jietu20240408-123322@2x.jpg"'
```

**Comment by Pai-Po** [comment]
ok，复制了你的命令测试修改了下，搞定了；有两个点需要注意：
1. URL中不包含v2
2. 路径中无法使用$HOME环境变量 （这个可能和curl版本有关）
