### ISSUE TITLE
推消息API，如果换行，则发不出去

### ISSUE THREAD

**Issue by jingjining1** [danni-cool/wechatbot-webhook#208]
⚠️不按照以下格式创建的issue将不会获得回复⚠️ 

## 提bug前先检查以下是否已经执行

- [x] 我已更新了最新版本的代码
- [x] 我已经仔细地阅读了readme 文档
- [x] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [x] 我已经尝试搜索过历史关闭issue寻找可能的答案

## bug描述
有时候一句话问题并不知道在描述什么

所以请按以下格式描述问题：

- **场景**：推消息API，如果换行，则发不出去
- **操作**：可以回复不换行的文本，但是用函数或者GPT进行换行，文本则发不出去

**Comment by danni-cool** [comment]
文字换行请使用转义字符 `\n`

```
{
    "to": "TestUser",
    "data": [{
            "type": "text",
            "content": "你好👋\n Stranger"
        }]
}
```

**Comment by jingjining1** [comment]
我是获取的自定义内容，请看下面的截图
![微信图片_20240408163917](https://github.com/danni-cool/wechatbot-webhook/assets/133858747/a0b0bccb-1024-4b67-aa7b-4bc878189ec8)
![微信图片_20240408163910](https://github.com/danni-cool/wechatbot-webhook/assets/133858747/1aefbe0a-a48b-4358-84ec-9307c64bcc1e)
能发送成功的是企业微信内部群，然后到推消息API这就发送不出去了，最后感谢回复

**Comment by jingjining1** [comment]
补充下
![微信截图_20240408165012](https://github.com/danni-cool/wechatbot-webhook/assets/133858747/6d3ccaa1-a581-4f7e-a502-e4425a9c3d6b)

这个是目前能推信息到微信的；然后我把内容进行换行，就发不出了；而企业微信内部群是可以的，如下图所示
![微信截图_20240408165012](https://github.com/danni-cool/wechatbot-webhook/assets/133858747/a5647db3-2de3-4720-a2f1-37684c823c62)

**Comment by lmm214** [comment]
"content": JSON.stringify(data)
问了 AI 说是要这样，测试通过
