### ISSUE TITLE
补充换行发不出信息的说明

### ISSUE THREAD

**Issue by jingjining1** [danni-cool/wechatbot-webhook#209]
⚠️不按照以下格式创建的issue将不会获得回复⚠️ 

## 提bug前先检查以下是否已经执行

- [x] 我已更新了最新版本的代码
- [x] 我已经仔细地阅读了readme 文档
- [x] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [x] 我已经尝试搜索过历史关闭issue寻找可能的答案

## bug描述
补充换行发不出信息的说明

所以请按以下格式描述问题：

- **场景**：换行的发不出的问题
- **操作**：用函数或者GPT处理后的信息，已经尝试多次
- **表现**：发送的信息是获取的信息数据

## 提供有用的信息
![微信截图_20240408165023](https://github.com/danni-cool/wechatbot-webhook/assets/133858747/7eba9bcf-5e27-4abe-8d61-ddfe01a16dfd)

这个是目前能推信息到微信的；然后我把内容进行换行，就发不出了；而企业微信内部群是可以的，如下图所示
![微信截图_20240408165012](https://github.com/danni-cool/wechatbot-webhook/assets/133858747/40530737-56d2-43e8-8099-ffae8e62f31b)

**Comment by danni-cool** [comment]
请核对自己的字符串拼接
```
curl --location 'http://localhost:3001/webhook/msg/v2?token=FncnVI3ykEy9' \
--header 'Content-Type: application/json' \
--data '{
    "to": "Test",
    "data": [{
            "type": "text",
            "content": "【提示】欧元区4月Sentix投资者信心指数录得-5.9，为\n2022年2月以来新高。"
        }]
}'
```

**Comment by jingjining1** [comment]
放弃了，账号又被检测到了！研究了2天的时间！哎...
