### ISSUE TITLE
登录后报错，AxiosError: Request failed with status code 503，然后掉线

### ISSUE THREAD

**Issue by Eternallyl** [danni-cool/wechatbot-webhook#210]
⚠️不按照以下格式创建的issue将不会获得回复⚠️ 

## 提bug前先检查以下是否已经执行

- [ ] 我已更新了最新版本的代码
- [ ] 我已经仔细地阅读了readme 文档
- [ ] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [ ] 我已经尝试搜索过历史关闭issue寻找可能的答案

## bug描述
有时候一句话问题并不知道在描述什么

所以请按以下格式描述问题：

- **场景**：登录
- **操作**：扫码登录
- **表现**：短暂上线然后掉线

## 提供有用的信息
- 目前使用的版本号：最新版本
- 提供任何代码片段/日志/输出/截图 以便于帮助快速定位问题

[2024-04-17T03:09:52.935] [ERROR] - 
AxiosError: Request failed with status code 503
 
[2024-04-17T03:09:52.936] [ERROR] - 
AxiosError: Request failed with status code 503
 
[2024-04-17T03:10:05.734] [ERROR] - 
AxiosError: Request failed with status code 503
 
[2024-04-17T03:10:07.929] [ERROR] - 
AxiosError: Request failed with status code 503
 
[2024-04-17T03:10:12.159] [ERROR] - 
AxiosError: Request failed with status code 503
 
[2024-04-17T03:10:12.159] [ERROR] - 
Error: 连续3次同步失败，5s后尝试重启
 
[2024-04-17T03:10:17.383] [ERROR] - 
AxiosError: Request failed with status code 503

![image](https://github.com/danni-cool/wechatbot-webhook/assets/59507559/14b7e28c-43a2-49ee-a151-f7cf8c0173de)

**Comment by wizcs** [comment]
同样的问题，补充一些信息是这个连续N次同步失败
![image](https://github.com/danni-cool/wechatbot-webhook/assets/67365333/921b53a3-84ff-4988-9f27-e754e5d8d80b)

**Comment by danni-cool** [comment]
两位有无可能是被暂时封号了？

**Comment by danni-cool** [comment]
统一归为风控问题
