### ISSUE TITLE
功能请求：支持通过Webhook发送消息时@群成员

### ISSUE THREAD

**Issue by okatu-loli** [danni-cool/wechatbot-webhook#211]
⚠️不按照以下格式创建的issue将不会获得回复⚠️ 

**提出问题的背景**

在使用wechatbot-webhook进行日常操作时，经常需要在消息中提及（@）特定的群成员以引起其注意。目前的实现中，wechatbot-webhook 似乎不支持在通过webhook发送的消息中直接@群成员。这导致了沟通效率低下，因为群成员可能会忽视没有直接提及他们的消息。

**描述下你期望的方案**

我希望 wechatbot-webhook 能支持在发送消息时通过某种方式（例如在消息文本中包含特定的标记或代码）来@群友。这样可以确保消息能更有效地传达给特定的群成员，并提高响应速度。

**其他信息**
无附加代码/截图。期待的效果类似于大多数现代聊天平台，比如 微信 或 QQ，可以通过输入 '@' 后跟用户名来直接提及某人。

**Comment by danni-cool** [comment]
提的建议很好，可是web协议是不支持@ ，见 FAQ：https://github.com/danni-cool/wechatbot-webhook/issues/72
