### ISSUE TITLE
可以发送带引用的消息吗？

### ISSUE THREAD

**Issue by zhaqianyuan** [danni-cool/wechatbot-webhook#213]
⚠️不按照以下格式创建的issue将不会获得回复⚠️ 

## 提bug前先检查以下是否已经执行

- [ ] 我已更新了最新版本的代码
- [ ] 我已经仔细地阅读了readme 文档
- [ ] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [ ] 我已经尝试搜索过历史关闭issue寻找可能的答案

## bug描述
有时候一句话问题并不知道在描述什么

所以请按以下格式描述问题：

- **场景**：
- **操作**：
- **表现**：

## 提供有用的信息
- 目前使用的版本号：（很可能最新版本已经修复了）
- 提供任何代码片段/日志/输出/截图 以便于帮助快速定位问题

**Comment by danni-cool** [comment]
refer to FAQ 4.1
