### ISSUE TITLE
隔一段时间会自动登出，调用api发送消息时报you must login first

### ISSUE THREAD

**Issue by fangchaodd** [danni-cool/wechatbot-webhook#217]
## bug描述
已使用了最新的docker镜像部署，并且加上了定时重启容器的定时任务（每小时重启一次）。但是隔一天左右还是会自动登出，看日志上会报错：
 扫描以下二维码以登录
 Or Access the URL to login: http://localhost:3001/login?token=775i-hjAFvHZ 
 [2024-05-14T00:42:19.147] [ERROR] - 
 AssertionError: 400 != 400

**Comment by danni-cool** [comment]
掉线和重启无关，这个是微信服务器让你登录态掉了

**Comment by fangchaodd** [comment]
> 掉线和重启无关，这个是微信服务器让你登录态掉了

现在发布到服务器后一段时间就会掉，还得重新扫码登录。怎么能比较稳定的让其不掉线或少掉线呢？

**Comment by fangchaodd** [comment]
> 掉线和重启无关，这个是微信服务器让你登录态掉了

您好，这种情况有什么解决方案吗

**Comment by danni-cool** [comment]
暂时无解
