### ISSUE TITLE
docker 部署完 调用测试发送api 出现 1204 == 0

### ISSUE THREAD

**Issue by yhq7111** [danni-cool/wechatbot-webhook#218]
⚠️不按照以下格式创建的issue将不会获得回复⚠️ 

## 提bug前先检查以下是否已经执行

- [x] 我已更新了最新版本的代码
- [x] 我已经仔细地阅读了readme 文档
- [x] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [x] 我已经尝试搜索过历史关闭issue寻找可能的答案

## bug描述
虚拟机docker部署
系统 centos 7 

入参 
{
    "to": "Qi",
    "data": [{

            "content": "你好👋\n Stranger"
        }]
}
postman 调用测试接口
所以请按以下格式描述问题：
{
    "success": false,
    "message": "All Messages (1) sent failed, look up data of task for more detail",
    "task": {
        "successCount": 0,
        "totalCount": 1,
        "failedCount": 1,
        "reject": [],
        "sentFailed": [
            {
                "to": "Qi",
                "data": [
                    {
                        "content": "你好👋\n Stranger",
                        "error": "AssertionError [ERR_ASSERTION]: 1204 == 0"
                    }
                ]
            }
        ],
        "notFound": []
    }
}

**Comment by danni-cool** [comment]
https://github.com/wechaty/wechaty/issues/2503

**Comment by yhq7111** [comment]
> [wechaty/wechaty#2503](https://github.com/wechaty/wechaty/issues/2503)

但是 我试过了 ，调用接口给 华为发送 就会出现这个报错，并且发不出去  苹果看是正常的，请问这是接受端系统的原因嘛

**Comment by danni-cool** [comment]
可能是你给某个账户发送太频繁了，然后暂时被限制了

**Comment by danni-cool** [comment]
今天的小号给自己发消息也遇到了这个问题，终究还是被限制了。

**Comment by danni-cool** [comment]
一般风控问题不属于解决范畴，所以先关闭了，faq记录+1

**Comment by YiMengYanYu** [comment]
啊我也这样

**Comment by YiMengYanYu** [comment]
限制一般多久解除

**Comment by danni-cool** [comment]
1天到数天不等
