### ISSUE TITLE
新添加的好友 没办法 马上交流 只能重新登录后 

### ISSUE THREAD

**Issue by yhq7111** [danni-cool/wechatbot-webhook#222]
⚠️不按照以下格式创建的issue将不会获得回复⚠️ 

## 提bug前先检查以下是否已经执行

- [x] 我已更新了最新版本的代码
- [x] 我已经仔细地阅读了readme 文档
- [x] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [x] 我已经尝试搜索过历史关闭issue寻找可能的答案
## bug描述

新添加的好友 没办法 马上交流 只能重新登录后 
![image](https://github.com/danni-cool/wechatbot-webhook/assets/41350661/91c366cd-e98a-42f6-941a-9b938f577f3b)

**Comment by danni-cool** [comment]
之前尝试过修复，处理起来比预期要麻烦，最近看看这个问题

**Comment by danni-cool** [comment]
重复问题先关闭了

**Comment by a76659197** [comment]
> 之前尝试过修复，处理起来比预期要麻烦，最近看看这个问题 #64

是不是换个思路，有没有办法拿到好友的微信号或者openid之类的，再调用第三方接口根据微信号或者id去拿到name补填进来。

**Comment by danni-cool** [comment]
> > 之前尝试过修复，处理起来比预期要麻烦，最近看看这个问题 #64
> 
> 是不是换个思路，有没有办法拿到好友的微信号或者openid之类的，再调用第三方接口根据微信号或者id去拿到name补填进来。

是有可能，但是比较耗费时间，考虑wechaty也不修我修起来费劲的原则，还是等有缘人贡献pr吧
