### ISSUE TITLE
- npm -g 安装后，运行 wxbot 报错

### ISSUE THREAD

**Issue by Yongest** [danni-cool/wechatbot-webhook#227]
- **场景**：
- npm -g 安装后，运行 wxbot
- **操作**：
 运行命令： wxbot
- **表现**：
- TypeError: Object prototype may only be an Object or null: undefined
![image](https://github.com/danni-cool/wechatbot-webhook/assets/25690725/99378a0f-2b48-43da-9b00-c327be070f35)

## 提供有用的信息
- 目前使用的版本号：node.-V 16.20.2

**Comment by danni-cool** [comment]
请使用 node 18+ 版本
