### ISSUE TITLE
是否可以在群聊里发送消息时@所有人

### ISSUE THREAD

**Issue by x99iONE** [danni-cool/wechatbot-webhook#228]
⚠️不按照以下格式创建的issue将不会获得回复⚠️ 

**提出问题的背景**
是否可以在群聊里发送消息时@所有人

好的建议经常需要结合问题发生的背景以给出最佳方案，所以描述下遇到这个问题的场景。

**描述下你期望的方案**
能够@所有人

你想要的功能是？
@所有人

**其他信息**
提供代码/截图/日志/输出等必要文件辅助描述

**Comment by danni-cool** [comment]
目前不支持，底层原理是基于web版微信，它也不支持，日后替换了底层协议可能会支持，看具体进度
