### ISSUE TITLE
windows版本的微信可以支持微信号回复吗，或者有固定的id区分

### ISSUE THREAD

**Issue by glwhappen** [danni-cool/wechatbot-webhook#231]
⚠️不按照以下格式创建的issue将不会获得回复⚠️ 

**提出问题的背景**

现在用网页版有两个体验很不好
1. 刚加上的好友没办法对话
2. 只能通过用户昵称区分，不太好

**描述下你期望的方案**

web版可能由于限制无法添加这个功能，请问windows版本可以吗，因为目前看到他们的api是一样的，所以问一下

**其他信息**
无

**Comment by danni-cool** [comment]
现在用网页版有两个体验很不好

刚加上的好友没办法对话
只能通过用户昵称区分，不太好
---------------------------------
web版确实体验不好，没有啥折腾空间了
web协议没法拥有固定id，windows hooks版本是有的，项目为了抹平底层手动造轮子的复杂性，尽量在api层提供一致体验。
只是还需要更多时间去封装底层
