### ISSUE TITLE
机器人配置问题

### ISSUE THREAD

**Issue by RichardMiku** [danni-cool/wechatbot-webhook#246]
大佬，我在创建机器人以后想要修改收消息api的地址，我要在哪里修改它？

**Comment by danni-cool** [comment]
关注下readme 里docker配置部分

**Comment by RichardMiku** [comment]
我在docker-compose中配置了环境变量，但是我进入docker容器中使用export修改了RECVD_MSG_API并重启机器人时，RECVD_MSG_API在机器人中并未做出改变

**Comment by danni-cool** [comment]
刚用项目里的 compose 文件验证过了，没啥问题 https://github.com/danni-cool/wechatbot-webhook/blob/main/docker-compose.yml

**Comment by RichardMiku** [comment]
![image](https://github.com/user-attachments/assets/7f2104f7-2057-484e-95d0-8248c2a710fe)
sorry，这貌似是docker的原因，只能通过重建容器的方式修改了
