### ISSUE TITLE
接收消息的接口，一直报不规范

### ISSUE THREAD

**Issue by liberalchang** [danni-cool/wechatbot-webhook#248]
这个是接口的测试
![image](https://github.com/user-attachments/assets/c72b1495-f97f-402e-a6bf-64acde93af15)
这个是我的配置
![image](https://github.com/user-attachments/assets/9b4a9f7f-ec8c-4728-913a-f80de3388a01)
这个是错误日志
![image](https://github.com/user-attachments/assets/59dacdfe-4021-493d-ab3b-eaec0a83f4d7)

**Comment by danni-cool** [comment]
docker 配置的时候去掉双引号
