### ISSUE TITLE
怎么自动同意好友请求呢

### ISSUE THREAD

**Issue by ywd727** [danni-cool/wechatbot-webhook#249]
⚠️不按照以下格式创建的issue将不会获得回复⚠️ 

**提出问题的背景**

好的建议经常需要结合问题发生的背景以给出最佳方案，所以描述下遇到这个问题的场景。

**描述下你期望的方案**

你想要的功能是？

**其他信息**
提供代码/截图/日志/输出等必要文件辅助描述

**Comment by danni-cool** [comment]
readme有写，此类问题直接关了
