### ISSUE TITLE
本地能打包和安装吗？我想打包在另一台电脑上试试。

### ISSUE THREAD

**Issue by lyanlai** [danni-cool/wechatbot-webhook#261]
⚠️不按照以下格式创建的issue将不会获得回复⚠️ 

## 提bug前先检查以下是否已经执行

- [x] 我已更新了最新版本的代码
- [x] 我已经仔细地阅读了readme 文档
- [x] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [x] 我已经尝试搜索过历史关闭issue寻找可能的答案

## bug描述
有时候一句话问题并不知道在描述什么

所以请按以下格式描述问题：

- **场景**：vscode打包并在另一台电脑安装后可以运行
- **操作**：npm run build
- **表现**：error

## 提供有用的信息
- 目前使用的版本号：node 18.17.0
- 提供任何代码片段/日志/输出/截图 以便于帮助快速定位问题
- 
![image](https://github.com/user-attachments/assets/3a69e685-1619-4d2e-b6f7-bc2307d6cc9c)

是不是要自己弄那个scrip才行？

**Comment by danni-cool** [comment]
只是运行为什么不用 `npx wechatbot-webhook`

**Comment by lyanlai** [comment]
> 只是运行为什么不用 `npx wechatbot-webhook`

![image](https://github.com/user-attachments/assets/166215de-8755-4167-a270-87614834c963)
我是想打包，打包好后好给另一个人使用机器人，不想把代码，vscode这些软件又在那台电脑上安装一遍，所以就想着打包好后在他电脑安装就行了。发现执行pmpm那个命令后没有打包好的东西，所以有疑问是目前是不是不支持打包安装的。

**Comment by danni-cool** [comment]
是的，不支持
