### ISSUE TITLE
有发送方唯一的身份识别id吗？

### ISSUE THREAD

**Issue by RichardMiku** [danni-cool/wechatbot-webhook#263]
有没有唯一确定身份的id识别码，可以获取微信号吗？我做了一个校园网查课表的，我应该如何防止他人改名用相同微信昵称导致机器人误判获取返回他人信息？我看了一下source里面的id好像不是固定的

**Comment by danni-cool** [comment]
都是不固定的，web协议就这样，想要功能稳定上 windows协议，但是那个还没组装，你可以研究下wechatferry
