### ISSUE TITLE
弹不出二维码 https://localhost:3001/login?token=[YOUR_PERSONAL_TOKEN]请求超时

### ISSUE THREAD

**Issue by qianqiuZjx** [danni-cool/wechatbot-webhook#267]
⚠️不按照以下格式创建的issue将不会获得回复⚠️ 

## 提bug前先检查以下是否已经执行

- [ ] 我已更新了最新版本的代码
- [ ] 我已经仔细地阅读了readme 文档
- [ ] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [ ] 我已经尝试搜索过历史关闭issue寻找可能的答案

## bug描述
有时候一句话问题并不知道在描述什么

所以请按以下格式描述问题：

- **场景**：
- **操作**：
- **表现**：

## 提供有用的信息
- 目前使用的版本号：（很可能最新版本已经修复了）
- 提供任何代码片段/日志/输出/截图 以便于帮助快速定位问题
必须要翻才能弹出二维码吗

**Comment by qianqiuZjx** [comment]
https://wechaty.js.org/qrcode/这个地址用手机5G网络就可以访问,4G网络就不行,pc端的话,用梯子就能访问,要不然也请求超时

**Comment by danni-cool** [comment]
二维码生成确实也不用依赖这个网址

**Comment by qianqiuZjx** [comment]
> 二维码生成确实也没有必要依赖这个网址

您的意思是写一个生成微信登录二维码的方法替换就可以了吗

**Comment by qianqiuZjx** [comment]
> 二维码生成确实也没有必要依赖这个网址

方便给个思路吗,感谢

**Comment by qianqiuZjx** [comment]
> 二维码生成确实也没有必要依赖这个网址

方便告诉一下怎么做或者给个思路吗,感谢

**Comment by danni-cool** [comment]
我来改，等发版

**Comment by qianqiuZjx** [comment]
> 我来改，等发版
感谢大佬
