### ISSUE TITLE
小白求助，关于接收消息的配置

### ISSUE THREAD

**Issue by NimbleCat** [danni-cool/wechatbot-webhook#283]
⚠️不按照以下格式创建的issue将不会获得回复⚠️ 

## 提bug前先检查以下是否已经执行

- [√] 我已更新了最新版本的代码
- [√] 我已经仔细地阅读了readme 文档
- [√] 我已在[FAQ](https://github.com/danni-cool/wechatbot-webhook/issues/72)里查找了可能寻找的答案
- [√] 我已经尝试搜索过历史关闭issue寻找可能的答案

## bug描述
我使用docker compose.yml启动，配置如下
`version: '3.8'
services:
  wxBotWebhook:
    image: dannicool/docker-wechatbot-webhook
    container_name: wxbot_app
    volumes:
      - ./wxBot_logs:/app/log
    ports:
      - "3001:3001"
    environment:
      - LOG_LEVEL=info
      - RECVD_MSG_API="http://10.2.24.4:7493/message" # 这个是云服务器的内网ip，公网ip尝试后也是相同的报错
    restart: unless-stopped
`
 配置参数 RECVD_MSG_API: "http://10.2.24.4:7493/message" <- 不符合 URL 规范, 该 API 将不会收到请求

看到有这样的问题，但是没哟解决办法【大哭】，然后尝试用dokcer run命令，会报错SyntaxError: Unexpected token ':' 。去掉http://也不行
## 提供有用的信息
- 目前使用的版本号：
-
![image](https://github.com/user-attachments/assets/a2a1a53c-a6a3-4946-b18f-c69eb006df60)

- 提供任何代码片段/日志/输出/截图 以便于帮助快速定位问题
![image](https://github.com/user-attachments/assets/fb66e421-e11d-4507-88c1-889bd89e6267)

**Comment by danni-cool** [comment]
去掉引号
