### ISSUE TITLE
AssertionError: 1205 == 0  或者 AssertionError: -1 == 0 被微信踢下线后，再次登陆 got more than 2room 错误

### ISSUE THREAD

**Issue by danni-cool** [danni-cool/wechatbot-webhook#60]
当再登录后,会报,但好像不是所有的都爆.大部分都会爆.
WARN Room find() got more than one(2) result

_Originally posted by @pkptzx in https://github.com/danni-cool/docker-wechatbot-webhook/issues/59#issuecomment-1813901334_
 
同样问题issue： 

- https://github.com/danni-cool/docker-wechatbot-webhook/issues/58

**Comment by jiyuhei** [comment]
文件传输都不能用了，估计是被封禁了，封多久不知道，我今天才被踢下了

**Comment by jiyuhei** [comment]
这个接口能不能支持企业微信的外部群呢？如果支持的话，是不是就可以解决web封禁的问题呢？

**Comment by danni-cool** [comment]
> 这个接口能不能支持企业微信的外部群呢？如果支持的话，是不是就可以解决web封禁的问题呢？

无意向支持，那个很复杂流程长，不在考虑范围内

**Comment by danni-cool** [comment]
> 文件传输都不能用了，估计是被封禁了，封多久不知道，我今天才被踢下了

应该还是和个人行为有关？我试了下没问题

**Comment by jiyuhei** [comment]
> > 文件传输都不能用了，估计是被封禁了，封多久不知道，我今天才被踢下去
> 
> 应该还是和个人行为有关？我试了下没问题

应该是我的问题，但是我就在自己团队群里发一些推送，没有人举报。还是被踢下来了

**Comment by danni-cool** [comment]
@jiyuhei web协议，踢下线是常态

**Comment by jiyuhei** [comment]
> @jiyuheiweb协议，踢下线是常态

登陆不了了，我坚持了将近一个月没掉线，今天下午掉线登陆不了了

**Comment by jiyuhei** [comment]
> @jiyuheiweb协议，踢下线是常态

今天发现微信web登陆已经解开了，封禁了一天左右

**Comment by samz2z** [comment]
下线很简单，就聊天界面顶上有个桌面微信，退出就好
