### ISSUE TITLE
[alpha] wine + docker + Windows 版微信计划

### ISSUE THREAD

**Issue by danni-cool** [danni-cool/wechatbot-webhook#66]
> [!CAUTION]
> 目前该分支正在 WIP 中，如果遇到预期之外的问题，请留言

## 背景

- windows协议替换web协议版本  https://github.com/danni-cool/docker-wechatbot-webhook/issues/22 分支：windows

## 目前尝试方案(基于wechaty-puppet-engine + hook）
- wine环境 和 docker 相关
    - [x] 解决 wine 环境Windows 版本 Node 无法运行的问题，以及 sidecar 的 frida 模块找不到 Process的问题
    - [x] 解决无法运行wechat的问题
    - [x] 解决遇到wsl编译的微信但在纯ubuntu上dockfile构建不成功 https://github.com/danni-cool/docker-wechatbot-webhook/issues/54
    - [x] 替换 sureer/wine-box:8.0.2（占用率极高）100% -> 50%
    - [x] 重新编写镜像
    - [x] wine 环境重启崩溃无法重启问题修复
    - [x] 降级windows版本，使用hook版本，确保成功
    - [x] nodeService 跟随docker镜像自动化 

 - windows 服务部署
   - [x] 使用hook版本  替换frida协议
   - [ ] webhook 服务编写

历史方案（废弃）(基于puppet-wechaty-xp)

**Comment by danni-cool** [comment]
@dgo2dance 貌似你百度也上不去，docker容器没网吗

**Comment by dgo2dance** [comment]
> @dgo2dance 重新创建容器、桥接网络等，先排除下环境因素

重新创建容器可以了，收发消息目前分支可以吗

**Comment by danni-cool** [comment]
> > @dgo2dance 重新创建容器、桥接网络等，先排除下环境因素
> 
> 重新创建容器可以了，收发消息目前分支可以吗

我再推一个镜像上去，目前都得手动（启动服务、安装微信、崩溃后重启等），功能支持性看issue

**Comment by KevinGong2013** [comment]
discord可以邀请一下不？

**Comment by danni-cool** [comment]
@KevinGong2013 https://discord.gg/GFXwsqKG

**Comment by dgo2dance** [comment]
> @dgo2dance 重新推了windows镜像 和 更新了readme

确实会存在机率 应用崩溃的问题

**Comment by dgo2dance** [comment]
> > @dgo2dance 重新推了windows镜像 和 更新了readme
> 
> 确实会存在机率 应用崩溃的问题

应用崩溃的问题，有思路吗，崩溃是影响可用性

**Comment by danni-cool** [comment]
@dgo2dance WIP 分支，暂时无法保证稳定可用性，还有很多底层问题要解决，有兴趣可以一起研究

**Comment by techctu** [comment]
安装完成后发现还是很容易崩溃，正在想办法定位问题。目前发现崩溃后重启字体就会失效，出现口口口口。

**Comment by danni-cool** [comment]
@techctu 目测是frida守护启动问题，后面有计划下掉这个服务，字体的话不前不打算解决

**Comment by danni-cool** [comment]
> 有无可能支持读取公众号的api？想把关注的公众号的推文用rss输出给阅读器

https://docs.rsshub.app/routes/social-media#xin-bang-wei-xin-gong-zhong-hao

**Comment by danni-cool** [comment]
@ShiFangJuMie 一个推文多篇文章是如何实现的，不是每次推文通过bot的收消息接口，入库一次吗

**Comment by 9k001** [comment]
> 我将这两天折腾公众号转RSS这件事整理了一下，发布在这里：
> 
> https://linux.do/t/topic/15122/1

重新发一下吧，没有了

**Comment by 9k001** [comment]
> > > 我将这两天折腾公众号转RSS这件事整理了一下，发布在这里：
> > > https://linux.do/t/topic/15122/1
> > 
> > 
> > 重新发一下吧，没有了
> 
> 被站长移入高级区了，不登录以后水点帖子升级，没法看到了=、= 我发个副本 https://granite-ocarina-4d0.notion.site/RSS-RSS-e960f34f46d44321b2c2add9ed1f0a2e?pvs=4

我还专门注册了一个号进去，还是没给看。
我反复看了半天，业务逻辑是

wechatbot-webhook 获得公众号文章 -->webhook--> 发送至 Python Flask  Docker --> 生成 RSS

FreshRSS订阅上述RSS
我改天试试
 Python 的项目写的不错，给了很大的启发

**Comment by 9k001** [comment]
> 高级区里有很多好东西，要发点/回点帖子升到1级

空了常去看看。。。
你那个业务逻辑是我说得那样么？。。

**Comment by Jiabccc** [comment]
我现在有一个长期开机的windows虚拟机并长期登录着windows版微信，请问有没有什么方法可以利用这个使用bot呢？

**Comment by danni-cool** [comment]
@Jiabccc windows分支还有很多问题，目前计划替换掉原先基于puppet-xp那套，所以暂时还不能稳定部署和调用，目前可稳定运行的仍然是web协议，windows 协议会有空陆续迭代

**Comment by danni-cool** [comment]
> linux版微信来了，不知是否有意义 https://www.52pojie.cn/thread-1896902-1-1.html

离可暴露api调用还差一个大神的距离

**Comment by techctu** [comment]
感谢分享。最近碰到puppet xp联系人缓存更新时间过长的问题，还没有找到解决办法。新联系人需要超过1天后才能获取，不知你是否有解决方案？发自我的iPhone------------------ 原始邮件 ------------------发件人: danni.cool  ***@***.***>发送时间: 2024年3月8日 11:42收件人: danni-cool/wechatbot-webhook ***@***.***>抄送: ctu ***@***.***>, Mention ***@***.***>主题: Re: [danni-cool/wechatbot-webhook] [alpha] wine + docker + Windows 版微信计划 (Issue #66)

linux版微信来了，不知是否有意义 https://www.52pojie.cn/thread-1896902-1-1.html

离可暴露api调用还差一个大神的距离

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/danni-cool/wechatbot-webhook/issues/66#issuecomment-1984988811",
"url": "https://github.com/danni-cool/wechatbot-webhook/issues/66#issuecomment-1984988811",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by danni-cool** [comment]
> 感谢分享。最近碰到puppet xp联系人缓存更新时间过长的问题，还没有找到解决办法。新联系人需要超过1天后才能获取，不知你是否有解决方案？发自我的iPhone------------------ 原始邮件 ------------------发件人: danni.cool ***@***.***>发送时间: 2024年3月8日 11:42收件人: danni-cool/wechatbot-webhook ***@***.***>抄送: ctu ***@***.***>, Mention ***@***.***>主题: Re: [danni-cool/wechatbot-webhook] [alpha] wine + docker + Windows 版微信计划 (Issue #66) linux版微信来了，不知是否有意义 https://www.52pojie.cn/thread-1896902-1-1.html 离可暴露api调用还差一个大神的距离 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***> [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[#66 (comment)](https://github.com/danni-cool/wechatbot-webhook/issues/66#issuecomment-1984988811)", "url": "[#66 (comment)](https://github.com/danni-cool/wechatbot-webhook/issues/66#issuecomment-1984988811)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

puppet-xp 调试起来问题很多，可以看看这个hook版本的https://gitee.com/daenmax/pc-wechat-hook-http-api

**Comment by techctu** [comment]
> > 感谢分享。最近碰到puppet xp联系人缓存更新时间过长的问题，还没有找到解决办法。新联系人需要超过1天后才能获取，不知你是否有解决方案？发自我的iPhone------------------ 原始邮件 ------------------发件人: danni.cool _**@**_._**>发送时间: 2024年3月8日 11:42收件人: danni-cool/wechatbot-webhook _**@**_.**_>抄送: ctu _**@**_._**>, Mention _**@**_.**_>主题: Re: [danni-cool/wechatbot-webhook] [alpha] wine + docker + Windows 版微信计划 (Issue #66) linux版微信来了，不知是否有意义 https://www.52pojie.cn/thread-1896902-1-1.html 离可暴露api调用还差一个大神的距离 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: _**@**_._**> [ { _**@**_.**_": "http://schema.org", _**@**_._**": "EmailMessage", "potentialAction": { _**@**_.**_": "ViewAction", "target": "[#66 (comment)](https://github.com/danni-cool/wechatbot-webhook/issues/66#issuecomment-1984988811)", "url": "[#66 (comment)](https://github.com/danni-cool/wechatbot-webhook/issues/66#issuecomment-1984988811)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { _**@**_.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
> 
> puppet-xp 调试起来问题很多，可以看看这个hook版本的https://gitee.com/daenmax/pc-wechat-hook-http-api

感谢回复，最近正好碰到ReadMe里提到的内存占用问题。

**Comment by hhhhhge** [comment]
> > > 感谢分享。最近碰到puppet xp联系人缓存更新时间过长的问题，还没有找到解决办法。新联系人需要超过1天后才能获取，不知你是否有解决方案？发自我的iPhone------------------ 原始邮件 ------------------发件人: danni.cool _**@**_._**>发送时间: 2024年3月8日 11:42收件人: danni-cool/wechatbot-webhook _**@**_.**_>抄送: ctu _**@**_._**>, Mention _**@**_.**_>主题: Re: [danni-cool/wechatbot-webhook] [alpha] wine + docker + Windows 版微信计划 (Issue #66) linux版微信来了，不知是否有意义 https://www.52pojie.cn/thread-1896902-1-1.html 离可暴露api调用还差一个大神的距离 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: _**@**_._**> [ { _**@**_.**_": "http://schema.org", _**@**_._**": "EmailMessage", "potentialAction": { _**@**_.**_": "ViewAction", "target": "[#66 (comment)](https://github.com/danni-cool/wechatbot-webhook/issues/66#issuecomment-1984988811)", "url": "[#66 (comment)](https://github.com/danni-cool/wechatbot-webhook/issues/66#issuecomment-1984988811)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { _**@**_.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
> > 
> > 
> > puppet-xp 调试起来问题很多，可以看看这个hook版本的https://gitee.com/daenmax/pc-wechat-hook-http-api
> 
> 感谢回复，最近正好碰到ReadMe里提到的内存占用问题。

这个的文档是不是要付费

**Comment by techctu** [comment]
hello，看一下这个  https://github.com/dockur/windows   没有采用wine而是使用qemu来虚拟化。我已经安装了win11，复制安装程序安装扫码登录了，还没弄开发环境。

**Comment by danni-cool** [comment]
> hello，看一下这个 https://github.com/dockur/windows 没有采用wine而是使用qemu来虚拟化。我已经安装了win11，复制安装程序安装扫码登录了，还没弄开发环境。

我理解整个windows镜像拖下来确实能解决很多环境报错问题，但是我想着是否可以做得极致一点，只提供必要的运行时环境，当然这个可能是最保险的方案。

**Comment by techctu** [comment]
> 我理解整个windows镜像拖下来确实能解决很多环境报错问题，但是我想着是否可以做得极致一点，只提供必要的运行时环境，当然这个可能是最保险的方案。

只提供必要的运行时环境有不少好处，比如能节约硬件资源，适合精简强干的精英团队。

**Comment by danni-cool** [comment]
@wtlihao web协议基本无大的折腾空间，推文诉求我推荐你使用[we-we-rss](https://github.com/cooderl/wewe-rss)

**Comment by 9k001** [comment]
> @wtlihao web协议基本无大的折腾空间，推文诉求我推荐你使用[we-we-rss](https://github.com/cooderl/wewe-rss)

看了一下 wewe-rss基于微信读书
我记得有提到过，微信读书接口容易被封。。。所以。。比较难。

**Comment by zcqzcq** [comment]
windows 安装python 报错
[backtrace.txt](https://github.com/user-attachments/files/16988043/backtrace.txt)

**Comment by danni-cool** [comment]
> windows 安装python 报错 [backtrace.txt](https://github.com/user-attachments/files/16988043/backtrace.txt)

故障现象：
不同环境现象不同，目前遇到以下几种
启动过程中Wine报错并退出
Wine启动立即报错并退出
xRDP连接报错
故障分析：
目前启动异常的情况，常见于使用旧发行版系统的服务器， 如：CentOS 7 (kernel 4.x)。
经验证，使用较新发行版系统的服务器，都可以正常运行。 如：Fedora 39/40 (kernel 6.x)
具体原因暂不明确，推测与内核版本有关。
解决方案：
建议使用较新的Linux发行版。

**Comment by BluerAngala** [comment]
发现另外一个开源项目，是基于 ipad 协议，提供了较多的API调用，可能会对本项目有所启发。

https://github.com/Devo919/Gewechat

同时，还有两个配套的项目：

1.js 调用 https://github.com/mikoshu/gewechaty
2.python 调用 https://github.com/hanfangyuan4396/gewechat-python

**Comment by danni-cool** [comment]
> 发现另外一个开源项目，是基于 ipad 协议，提供了较多的API调用，可能会对本项目有所启发。
> 
> https://github.com/Devo919/Gewechat
> 
> 同时，还有两个配套的项目：
> 
> 1.js 调用 https://github.com/mikoshu/gewechaty 2.python 调用 https://github.com/hanfangyuan4396/gewechat-python

点个赞先，回头研究研究

**Comment by danni-cool** [comment]
https://github.com/danni-cool/wechatbot-provider-windows 其实可用，暂时没写web api，如果有需要的可以试试rpc调用
