### ISSUE TITLE
msg.js中追加存储发送者的name轮询及添加发送到多人多群的规则

### ISSUE THREAD

**Issue by rcy1314** [danni-cool/wechatbot-webhook#77]
如题，目前我在使用中无法读取和写入来自群内或单人会话者的昵称，添加http请求发送时也只能一次发送一个对象值，不能一次发送多个对象，需求1记录群内记录可追加发言者的昵称或需求2可将昵称参数加入到TG发送中：
上述两图传到了本仓库，如有不便请删除，需求3：在读取判断if函数时能记录name参数

**Comment by rcy1314** [comment]
自己尝试修改吧，建议修改为符合自己想要的对话逻辑和规则

**Comment by danni-cool** [comment]
这种可以加入discord详聊，感觉描述还是比较特定
