### ISSUE TITLE
掉线提醒（优化）

### ISSUE THREAD

**Issue by glwhappen** [danni-cool/wechatbot-webhook#86]
能否考虑增加一个掉线提醒的接口，和处理消息的接口一样就行了，如果掉线了，或者发生异常了，就调用这个接口，然后我继续做后续的逻辑处理，发邮件或者其他操作。

**Comment by danni-cool** [comment]
掉线会收到提醒，通过recvdAPi 接收，但是有时候掉线了wechaty 不认为掉线

**Comment by danni-cool** [comment]
方案补充：连续异常如果发生应该检测是否是掉线状态，通过设定一定规则尝试重新登录or触发logout，避免重复多次触发error事件

**Comment by shaojun-tes** [comment]
我是自己写脚本监控，隔几分钟请求一下/loginCheck接口，根据返回的success字段的true/false来判断是否掉线了，然后发信息给我。但是我正好有个疑问：当掉线以后，message会返回login的URL, 这个URL是算法生成的，还是调用wechat接口后返回的。如果是调用调用wechat接口返回，那么这个接口不能用于监控接口了。因为如果监控到掉线而没有及时处理，会导致频繁调用wechat服务器登陆接口。
···
{"success":false,"message":"https://wechaty.js.org/qrcode/https%3A%2F%2Flogin.weixin.qq.com%2Fl%2FAcpiVwlatg%3D%3D"}
···
我指的是https://wechaty.js.org/qrcode/之后的https%3A%2F%2Flogin.weixin.qq.com%2Fl%2FAcpiVwlatg%3D%3D这个是不是调用wechat服务器接口返回的？

**Comment by danni-cool** [comment]
> 我是自己写脚本监控，隔几分钟请求一下/loginCheck接口，根据返回的success字段的true/false来判断是否掉线了，然后发信息给我。但是我正好有个疑问：当掉线以后，message会返回login的URL, 这个URL是算法生成的，还是调用wechat接口后返回的。如果是调用调用wechat接口返回，那么这个接口不能用于监控接口了。因为如果监控到掉线而没有及时处理，会导致频繁调用wechat服务器登陆接口。
> 
> ```
> {"success":false,"message":"https://wechaty.js.org/qrcode/https%3A%2F%2Flogin.weixin.qq.com%2Fl%2FAcpiVwlatg%3D%3D"}
> ```
> 
> 我指的是https://wechaty.js.org/qrcode/. 之后的. https%3A%2F%2Flogin.weixin.qq.com%2Fl%2FAcpiVwlatg%3D%3D这个URL是不是调用wechat服务器接口返回的？

其实没必要轮询，收消息接口可以接到这个事件。因为这个其实也是触发了wechaty的 logout事件，我去标记success 为false，但是真实情况是wechaty未触发这个事件就已经掉线了，

这个是正常登录扫码接口，本身就是要轮询微信的登录地址的。

**Comment by shaojun-tes** [comment]
好的，非常感谢解答，那我还是通过recvdAPi 接收消息处理

**Comment by shaojun-tes** [comment]
顺便借此说下，希望增加一个像 /healthz 健康检测的接口，这样可以使用监控对这个服务的状态做个存活检测之类的，谢谢！

**Comment by danni-cool** [comment]
好像wechat-puppet修了这个问题，最近更新可以了，观察一段时间如果还有问题再完善该issue
