### ISSUE TITLE
扫码之后没有任何反应

### ISSUE THREAD

**Issue by njroye** [danni-cool/wechatbot-webhook#88]
微信已经实名认证并且也已经绑定微信支付，扫描二维码后没有任何反应，这是啥情况哈？

**Comment by danni-cool** [comment]
手机端显示登录了吗？

**Comment by qinfne** [comment]
没有

**Comment by firefoxmmx2** [comment]
我的情况和他一样，使用的latest的镜像， 扫码登录后，实际上没有完成登录，打开日志报错了。如下
`> docker-wechatbot-webhook@2.4.1 prestart
> node ./scripts/preStart

.env file created from .env.example
检测未配置 LOGIN_API_TOKEN, 写入初始化值 LOCAL_LOGIN_API_TOKEN=KacQ~CNA6d.6  => .env 


> docker-wechatbot-webhook@2.4.1 start
> node main

Access the URL to login: http://localhost:3001/login?token=KacQ~CNA6d.6

AssertionError: 1 == 0

starting fetching api: http://192.168.31.235:9091 [
  '----------------------------662582234714748296541846\r\n' +
    'Content-Disposition: form-data; name="source"\r\n' +
    '\r\n',
  '{"room":"","to":"","from":""}',
  [Function: bound ],
  '----------------------------662582234714748296541846\r\n' +
    'Content-Disposition: form-data; name="isSystemEvent"\r\n' +
    '\r\n',
  '1',
  [Function: bound ],
  '----------------------------662582234714748296541846\r\n' +
    'Content-Disposition: form-data; name="isMentioned"\r\n' +
    '\r\n',
  '0',
  [Function: bound ],
  '----------------------------662582234714748296541846\r\n' +
    'Content-Disposition: form-data; name="type"\r\n' +
    '\r\n',
  'text',
  [Function: bound ],
  '----------------------------662582234714748296541846\r\n' +
    'Content-Disposition: form-data; name="content"\r\n' +
    '\r\n',
  '{"event":"error","error":{"code":2,"details":"AssertionError [ERR_ASSERTION]: 1 == 0\\n    at Object.equal (/app/node_modules/wechat4u/lib/util/global.js:69:24)\\n    at /app/node_modules/wechat4u/lib/core.js:229:24\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","message":"1 == 0","name":"AssertionError","stack":"AssertionError [ERR_ASSERTION]: 1 == 0\\n    at Object.equal (/app/node_modules/wechat4u/lib/util/global.js:69:24)\\n    at /app/node_modules/wechat4u/lib/core.js:229:24\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"user":null}',
  [Function: bound ]
]
`

**Comment by firefoxmmx2** [comment]
我好像是没有绑银行卡，现在可以登录了
