### ISSUE TITLE
微信 Bot 收不到消息

### ISSUE THREAD

**Issue by Saltrol** [danni-cool/wechatbot-webhook#97]
我使用 Golang 写了一个简单的 收到 POST 在控制台打印出表单的数据，经过 APIFOX 测试该接口可以正常打印信息，部署到服务器后，测试还是没有问题的，但是我给微信机器人发消息并没有接收到消息。

我的 收消息 Docker 启动项配置：`RECVD_MSG_API="http://1*3.56.24*.1*4:3002/receive_msg"`

我的 Golang 代码是：

```golang
package main

import (
	"bot/cors"

	"github.com/gin-gonic/gin"
)

// receive_msg
func receive_msg(c *gin.Context) {
	message := c.PostForm("message")
	println(message)
}

func main() {
	receive := gin.Default()
	receive.Use(cors.Cors())
	receive.POST("/receive_msg", receive_msg)
	receive.Run("0.0.0.0:3002")
}
```

请问我该怎么去解决这个问题呢？谢谢。

**Comment by danni-cool** [comment]
看下docker 日志，调用该接口成功了吗，收消息一般会在docker日志里有一条上报的日志

**Comment by Saltrol** [comment]
![image](https://github.com/danni-cool/wechatbot-webhook/assets/106380305/ad60da42-e85a-42c5-93cd-5ed927725356)
是这个样子吗？看样子是成功了？

**Comment by danni-cool** [comment]
![Jietu20231226-103318](https://github.com/danni-cool/wechatbot-webhook/assets/13482835/db40b9da-091e-4130-96b5-b0fd2f2c63fd)
大概这样，看起来并没有上报api
1. 检查下是否参数拼写错误 RECVD_MSG_API
2. 使用docker inspect [container id]检查参数有无被传递到容器内

**Comment by Saltrol** [comment]
![image](https://github.com/danni-cool/wechatbot-webhook/assets/106380305/7e0c333f-0e92-4f33-87af-437c27e427e9)
看样子好像是没错  T T

**Comment by danni-cool** [comment]
为啥你有两个 RECVD_MSG_API

**Comment by Saltrol** [comment]
这我也不清楚啊，是这个问题引起的吗？该怎么解决呢？😢

**Comment by Saltrol** [comment]
我已经把多余的那个空白的删掉了，似乎可以了，但是接收到的消息打印在控制台是空白的，是我程序写的有问题吗？
![1703561210455](https://github.com/danni-cool/wechatbot-webhook/assets/106380305/6f398089-e56c-4cdf-a8f2-9409838879f2)

**Comment by danni-cool** [comment]
POST 的是form data，找对应的处理包去处理前置请求

**Comment by Saltrol** [comment]
好的，谢谢，打扰您的时间了
