### ISSUE TITLE
无法在微信群发消息

### ISSUE THREAD

**Issue by Easen-L** [danni-cool/wechatbot-webhook#98]
对微信群发消息，结果返回没有找到该群
对微信群发消息，是否需要做特殊处理？
ps：对个人是可以，是可以发消息
![image](https://github.com/danni-cool/wechatbot-webhook/assets/60615862/23d066a9-2bf7-424d-869b-a277341757f8)

**Comment by danni-cool** [comment]
建议再仔细看下api文档
